// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/social-button/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { SocialButton } from './SocialButton.web';
export { SOCIAL_PROVIDERS } from './providers';
export { socialButtonLabel } from './SocialButton.web';
export type { SocialProvider } from './providers';
export type {
  SocialBrand,
  SocialButtonAction,
  SocialBrandConfig,
  SocialButtonAppearance,
  SocialButtonProps,
  SocialButtonSize,
} from './types';
