// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/select/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export {
  Select,
  SelectTrigger,
  SelectValue,
  SelectIcon,
  SelectContent,
  SelectItem,
} from './Select.web';
export {
  useSelectItemContext,
  SelectItemText,
  SelectItemIndicator,
  SelectSeparator,
  SelectGroup,
  SelectLabel,
  SelectScrollProvider,
  SelectScrollUpButton,
  SelectScrollDownButton,
} from './shared';
export type { SelectScrollContextValue } from './shared';
export type {
  SelectProps,
  SelectTriggerProps,
  SelectValueProps,
  SelectIconProps,
  SelectContentProps,
  SelectItemProps,
  SelectItemTextProps,
  SelectItemIndicatorProps,
  SelectGroupProps,
  SelectLabelProps,
  SelectSize,
} from './types';
