// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/alert-dialog/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

import { Dialog } from '../dialog/index.web';
import { createAlertDialog } from './AlertDialog';

/**
 * The declarative, CONTROLLED confirm dialog. The imperative counterpart is
 * `confirm()` from `@oxy.so/bloom/surfaces`, which presents onto the shared
 * surface stack — this family owns no queue and no host of its own.
 */
export const AlertDialog = createAlertDialog(Dialog);

export type { AlertDialogProps, AlertDialogActionStyle } from './types';
