// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/command/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

import { Dialog } from '../dialog/index.web';
import { createCommand } from './Command';

export const Command = createCommand(Dialog);

export type { CommandProps, CommandItem } from './types';
