// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/progressive-blur/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export type { ProgressiveBlurProps } from './types';
export {
  ProgressiveBlur,
} from './ProgressiveBlur.web';
