// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/bottom-sheet/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export {
  BottomSheet,
} from './BottomSheet.web';
export { default } from './BottomSheet.web';
export type { BottomSheetProps, BottomSheetRef } from './types';
