// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/loading/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Loading } from './Loading.web';
export { SpinnerIcon } from './SpinnerIcon.web';
export type {
  LoadingProps,
  LoadingVariant,
  LoadingSize,
  SpinnerLoadingProps,
  TopLoadingProps,
  InlineLoadingProps,
} from './types';
