// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/connection-dots/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ConnectionDots } from './ConnectionDots.web';
export type { ConnectionDotsProps } from './types';
