// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/chat-composer/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ChatComposer } from './ChatComposer';
export { ComposerBanner } from './ComposerBanner';
export { ComposerAttachmentStrip } from './ComposerAttachmentStrip';
export { ComposerIconButton } from './ComposerIconButton.web';
export { SuggestionList } from './SuggestionList';
export { VoiceRecorder } from './VoiceRecorder';
export { AttachmentMenu } from './AttachmentMenu';
export { EmojiPicker } from './EmojiPicker';
export { ReactionPicker } from './ReactionPicker';
export { MessageContextMenu } from './MessageContextMenu';
export {
  ATTACHMENT_MENU_ITEMS,
  EMOJI_CATEGORY_ICONS,
  REACTION_PICKER_EMOJIS,
  SKIN_TONE_MODIFIERS,
  applySkinTone,
  emojiChar,
  filterEmojiGroups,
  formatRecordingTime,
} from './shared';
export type {
  AttachmentMenuItem,
  AttachmentMenuProps,
  ChatComposerAttachment,
  ChatComposerIcon,
  ChatComposerLabels,
  ChatComposerProps,
  ChatComposerSendOn,
  ChatComposerSuggestion,
  ComposerAttachmentStripProps,
  ComposerBannerKind,
  ComposerBannerProps,
  ComposerIconButtonProps,
  EmojiEntry,
  EmojiGroup,
  EmojiPickerLabels,
  EmojiPickerProps,
  EmojiPickerTab,
  MessageContextMenuProps,
  MessageMenuItem,
  ReactionPickerProps,
  SuggestionKind,
  SuggestionListProps,
  VoiceRecorderLabels,
  VoiceRecorderProps,
  VoiceRecorderState,
} from './types';
