// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/multi-agent-chat/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export type {
  Agent as MultiAgentChatAgent,
  Conversation as MultiAgentChatConversation,
  Message as MultiAgentChatMessage,
  Workspace as MultiAgentChatWorkspace,
} from './data';
export { MultiAgentChat } from './MultiAgentChat.web';
export type { MultiAgentChatProps } from './types';
