/** Semantic utility names used by the component recipes. Values stay owned by Bloom's theme. */
export const COMPONENT_COLOR_ROLES = {
  'status-blue-background': 'var(--info-subtle)',
  'status-blue-text': 'var(--info-text)',
  'status-yellow-background': 'var(--warning-subtle)',
  'status-yellow-text': 'var(--warning-text)',
  'status-orange-background': 'var(--warning-subtle)',
  'status-orange-text': 'var(--warning-text)',
  'status-rose-background': 'var(--error-subtle)',
  'status-rose-text': 'var(--error-text)',
  'ticket-detail-surface': 'var(--card)',
  'ticket-detail-favorite': 'var(--warning)',
  'ticket-detail-low-background': 'var(--info-subtle)',
  'ticket-detail-low-text': 'var(--info-text)',
  'ticket-detail-low-hover': 'var(--info-subtle)',
  'ticket-detail-medium-hover': 'var(--warning-subtle)',
  'ticket-detail-high-hover': 'var(--warning-subtle)',
  'ticket-detail-urgent-hover': 'var(--error-subtle)',
  'ticket-detail-resource-background': 'var(--info-subtle)',
  'ticket-detail-resource-text': 'var(--info-text)',
  'project-board-empty-panel': 'var(--surface)',
  'project-board-empty-back': 'var(--muted)',
  'project-board-empty-middle': 'var(--popover)',
  'project-board-empty-front': 'var(--border)',
  'project-board-empty-detail': 'var(--card)',
  'background-full': 'var(--background)',
  'background-primary-default': 'var(--card)',
  'background-primary-hover': 'var(--surface)',
  'background-primary-active': 'var(--popover)',
  'background-secondary-default': 'var(--surface)',
  'background-secondary-hover': 'var(--popover)',
  'background-secondary-active': 'var(--accent)',
  'background-tertiary-default': 'var(--popover)',
  'background-tertiary-hover': 'var(--accent)',
  'background-tertiary-active': 'var(--muted)',
  'text-primary': 'var(--foreground)',
  'text-white': '#ffffff',
  'text-destructive': 'var(--error-text)',
  'foreground-icon-primary': 'var(--foreground)',
  'foreground-icon-secondary': 'var(--muted-foreground)',
  'foreground-icon-tertiary': 'var(--muted-foreground)',
  'border-button-default': 'var(--border)',
  'border-button-white': 'var(--input)',
  'border-focus-ring': 'var(--ring)',
  'border-input-default': 'var(--input)',
  'separator-border': 'var(--border)',
  'button-primary': 'var(--primary)',
  'dropdown-item-hover-background': 'var(--accent)',
  'accent-50': 'var(--primary-subtle)',
  'accent-100': 'var(--primary-subtle)',
  'accent-200': 'var(--primary-subtle)',
  'accent-300': 'var(--primary)',
  'accent-400': 'var(--primary)',
  'accent-500': 'var(--primary)',
  'accent-600': 'var(--primary-text)',
  'accent-700': 'var(--primary-text)',
  'accent-800': 'var(--primary-text)',
  'accent-900': 'var(--primary-text)',
  'accent-950': 'var(--primary-text)',
} as const;

/** Numeric utilities use the authored 4px grid on both platforms, independent of rem. */
export const COMPONENT_SPACING = Object.fromEntries(
  [
    0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 20,
    24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 72, 80, 96,
  ].map((value) => [String(value), `${value * 4}px`]),
);
export const COMPONENT_RADIUS = {
  xs: '2px',
  sm: '4px',
  md: '6px',
  lg: '8px',
  xl: '12px',
  '2xl': '16px',
  '3xl': '24px',
  '4xl': '32px',
  '2lg': '10px',
  '2-5xl': '20px',
} as const;
export const COMPONENT_CONTAINERS = {
  xs: '320px',
  sm: '384px',
  md: '448px',
  lg: '512px',
  xl: '576px',
} as const;
export const COMPONENT_SHADOWS = {
  sidebar:
    '0 1px 0 0 rgb(0 0 0 / 0.0196), 0 1px 12px 0 rgb(0 0 0 / 0.0588), 0 0 1px 0 rgb(0 0 0 / 0.3216)',
  card: '0 1px 1px 0 rgb(0 0 0 / 0.05)',
  dropdown: '0 1px 1px 0 rgb(0 0 0 / 0.04), 0 4px 4px 0 rgb(0 0 0 / 0.02)',
} as const;
