// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/frosted-icon-button/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { FrostedIconButton } from './FrostedIconButton.web';
export type { FrostedIconButtonProps, FrostedIconButtonSize } from './types';
