// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/dialog/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Dialog } from './Dialog.web';
export { useDialogContext, useDialogControl } from './context';
export { useDialogHeader } from './DialogHeader';
export { useDialogFrame } from './DialogMorph';
export type { DialogFrame } from './DialogMorph';
export type {
  DialogAction,
  DialogActionColor,
  DialogContextProps,
  DialogControlProps,
  DialogHeaderConfig,
  DialogInset,
  DialogPlacement,
  DialogProps,
  ResponsiveDialogPlacement,
} from './types';
export { BLOOM_DIALOG_CSS } from './Dialog.web';
