// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/media-flight/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { MediaFlightLayer } from './MediaFlightLayer.web';
export { MediaFlightHost } from './MediaFlightHost.web';
export { MediaSurface, MediaPoster, EmptyMediaSurface } from './MediaSurface';
export { useMediaFlight } from './use-media-flight';
export {
  DEFAULT_FLIGHT_CORNER_RADIUS,
  flightProgress,
  handOffFlight,
  hasFlight,
  releaseFlight,
  resetMediaFlight,
} from './store';
export { SURFACE_MOUNT_TIMEOUT_MS } from './constants';
export {
  loadExpoVideo,
  warnExpoVideoUnavailable,
  provideExpoVideo,
  resetExpoVideoModule,
  type ExpoVideoLike,
  type VideoPlayerLike,
  type VideoSurfaceContentFit,
  type VideoSurfaceType,
  type VideoViewLikeProps,
} from './expo-video-module';
export type {
  MediaFlight,
  MediaFlightAnchorNode,
  MediaFlightController,
  MediaFlightHostProps,
  MediaSurfaceVideoOf,
  MediaVideoSlot,
  MediaVideoSlotProps,
  MediaFlightOptions,
  MediaSurfaceContent,
  MediaSurfaceImage,
  MediaSurfaceVideo,
  MeasuredRect,
} from './types';
export type { MediaSurfaceProps } from './MediaSurface';
