// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/theme/color-scope/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { BloomColorScope, useColorScopeStyle } from './ColorScope.web';
export type { BloomColorScopeProps } from './ColorScope.web';
