// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/collapsible/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Collapsible } from './Collapsible.web';
export type { CollapsibleProps, CollapsibleFocusTarget } from './types';
