// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/composer-panel/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ComposerPanel } from './ComposerPanel.web';
export { ComposerAttachments } from './ComposerAttachments.web';
export { ModelPicker } from './ModelPicker.web';
export { ComposerPanelStatusTab } from './ComposerPanelStatusTab';
export { ComposerPill } from './ComposerPill.web';
export { ComposerStatusBar } from './ComposerStatusBar.web';
export {
  COMPOSER_PANEL_ADD_MENU,
  COMPOSER_PANEL_PERMISSIONS,
  MODEL_PICKER_EFFORT_LEVELS,
} from './shared';
export type {
  ComposerAttachmentsProps,
  ComposerPanelAddMenuGroup,
  ComposerPanelAddMenuRow,
  ComposerPanelAttachment,
  ComposerPanelAttachmentKind,
  ComposerPanelLabels,
  ComposerPanelPermissionOption,
  ComposerPanelProps,
  ComposerPanelStatusTabProps,
  ComposerPillLabels,
  ComposerPillProps,
  ComposerStatusBarFolder,
  ComposerStatusBarLabels,
  ComposerStatusBarProps,
  ModelPickerLabels,
  ModelPickerModel,
  ModelPickerProps,
  ModelPickerProvider,
} from './types';
