// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/hover-card/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { HoverCard, HoverCardTrigger, HoverCardContent } from './HoverCard.web';
export {
  HOVER_CARD_CLOSE_DELAY,
  HOVER_CARD_OPEN_DELAY,
  HOVER_CARD_SIDE_OFFSET,
} from './constants';
export type { HoverCardProps, HoverCardTriggerProps, HoverCardContentProps } from './types';
