// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/portal/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export {
  PortalProvider,
  PortalOutlet,
  Portal,
} from './Portal.web';
// The app-content half of a modal overlay: wrap everything EXCEPT the
// `PortalOutlet` in it. Lives in `overlay/` (it reads the modal registry) and is
// offered here because this is the subpath the app root already imports.
export { OverlayInertBoundary } from '../overlay/OverlayInertBoundary';
export type { OverlayInertBoundaryProps } from '../overlay/types';
