// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/fab/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Fab } from './Fab.web';
export type { FabProps, FabVariant, FabSize, FabPlacement, FabMinimizeBehavior } from './types';
