// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/zoomable-media-gallery/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ZoomableMediaGallery, ZoomableMediaGallery as default } from './ZoomableMediaGallery.web';
export type {
  ZoomableMediaGalleryHandle,
  ZoomableMediaGalleryProps,
  GalleryImage,
  GalleryVideo,
  GalleryMedia,
  MeasureThumb,
  MeasuredRect,
} from './types';
export * from './constants';
