// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/stat-bar/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Meter } from './Meter.web';
export { MeterRing } from './MeterRing';
export { StatBar } from './StatBar';
export { meterFraction, meterValue, resolveMeterColors } from './shared';
export type { MeterColors } from './shared';
export type {
  AnyMeterProps,
  MeterDecorativeProps,
  MeterProps,
  MeterRingProps,
  StatBarProps,
  StatBarProgressProps,
  StatBarSplitProps,
  StatBarVariant,
} from './types';
