// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/fonts/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { fontFamilies, fontCssVars } from './tokens';
export type { FontFamilyName } from './tokens';
export { applyFontFaces } from './apply-font-faces.web';
export { FONT_ASSETS } from './font-assets.web';
export { FontLoader } from './FontLoader';
export type { FontLoaderProps } from './FontLoader';
