// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/rating/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Rating } from './Rating';
export { RatingBar } from './RatingBar.web';
export { RatingInput } from './RatingInput';
export type {
  RatingBarProps,
  RatingCountStyle,
  RatingInputProps,
  RatingInputSize,
  RatingProps,
  RatingSize,
  RatingVariant,
} from './types';
