// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/ai-chat/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export {
  AiChatAssistantMessage,
  AiChatContainer,
  AiChatFeedbackRow,
  AiChatGalleryPanel,
  AiChatImageGeneration,
} from './AiChat.web';
export { AiChatCodePanel } from './AiChatCodePanel';
export { AiChatThread } from './AiChatContainer';
export {
  AiChatBullet,
  AiChatBulletList,
  AiChatLinkChip,
  AiChatMessageLine,
  AiChatStrong,
  AiChatUserMessage,
} from './AiChatMessages';
export { AiChatMobileHeader, AiChatResizeHandle, AiChatShell } from './AiChatShell';
export { useAiChatChromeInsets, useAiChatShell } from './context';
export type { AiChatChromeInsets, AiChatShellState } from './context';
export type {
  AiChatAssistantMessageProps,
  AiChatBulletListProps,
  AiChatBulletProps,
  AiChatChangedFile,
  AiChatCodePanelLabels,
  AiChatCodePanelProps,
  AiChatContainerLabels,
  AiChatContainerProps,
  AiChatFeedbackLabels,
  AiChatFeedbackRowProps,
  AiChatGalleryPanelLabels,
  AiChatGalleryPanelProps,
  AiChatGeneration,
  AiChatIconComponent,
  AiChatImageGenerationLabels,
  AiChatImageGenerationProps,
  AiChatLinkChipProps,
  AiChatMessageLineProps,
  AiChatMobileHeaderProps,
  AiChatPanelAction,
  AiChatPanelTab,
  AiChatResizeHandleProps,
  AiChatShellLabels,
  AiChatShellProps,
  AiChatStrongProps,
  AiChatThreadHandle,
  AiChatThreadProps,
  AiChatUserMessageProps,
} from './types';
