import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The `react-native` export condition must stay SPLIT into `types` + `default`.
 *
 * Metro compiles Bloom from source, so `default` points at `src/`. TypeScript
 * honours `react-native` as well (expo/tsconfig.base sets
 * `customConditions: ["react-native"]`), and if the condition were a bare
 * string every native-targeted consumer would type-check Bloom's own `.tsx`
 * files — pulling `react-dom` (from the web forks) and optional peers like
 * `expo-haptics` / `@react-native-community/netinfo` into a program that never
 * declared them. Measured against a consumer fixture with no
 * `@types/react-dom`, the string form produces TS7016 on
 * `src/portal/Portal.web.tsx`, TS2307 on `src/hooks/use-haptics.tsx` and
 * `src/connection-status/ConnectionStatusToasts.tsx`, plus a nativewind TS2769 on
 * `src/dialog/DialogHeader.tsx`. `skipLibCheck` cannot suppress any of them —
 * a `.tsx` is not a declaration file.
 *
 * Splitting the condition means tsc asks for `types` and gets the built
 * declarations, while Metro (which never requests `types`) still falls through
 * to `default` and bundles source. Verified end to end with a real
 * `expo export --platform ios`.
 *
 * `package.json#exports` is generated by `scripts/generate-platform-exports.mjs`
 * — fix a failure there, never by hand-editing `package.json`.
 */

type ExportEntry = Record<string, unknown>;

// Read rather than `import` the manifest: tsconfig pins `rootDir` to `src`, so
// a JSON import from outside it would drag package.json into the build program.
const PKG_PATH = join(__dirname, '..', '..', 'package.json');
const pkg = JSON.parse(readFileSync(PKG_PATH, 'utf8')) as {
  exports: Record<string, ExportEntry | string>;
};
const exportsMap = pkg.exports;

/** Non-subpath entries that are legitimately plain strings (static assets). */
const STRING_ENTRIES = [
  './design-tokens/theme.css',
  './design-tokens/tokens.json',
  './package.json',
];

/**
 * Vacuity floor, deliberately NOT the current count: a number written here goes
 * stale on the next family added or deleted, and a stale one reads as a
 * measurement. It exists only so a traversal bug that silently finds no
 * subpaths cannot pass. `SUBPATHS` in `scripts/generate-platform-exports.mjs`
 * is the actual list.
 */
const MIN_SUBPATHS = 80;

const subpathEntries = Object.entries(exportsMap).filter(
  (entry): entry is [string, ExportEntry] => typeof entry[1] !== 'string',
);

describe('package.json#exports — react-native condition', () => {
  it(`declares at least ${MIN_SUBPATHS} conditional subpaths`, () => {
    expect(subpathEntries.length).toBeGreaterThanOrEqual(MIN_SUBPATHS);
  });

  it('exposes only the known static assets as string exports', () => {
    const strings = Object.entries(exportsMap)
      .filter(([, value]) => typeof value === 'string')
      .map(([name]) => name);
    expect(strings.sort()).toEqual([...STRING_ENTRIES].sort());
  });

  it('splits every react-native condition into types + default, in that order', () => {
    const offenders: string[] = [];
    for (const [name, entry] of subpathEntries) {
      const condition = entry['react-native'];
      if (typeof condition !== 'object' || condition === null) {
        offenders.push(`${name}: react-native is ${JSON.stringify(condition)}, expected an object`);
        continue;
      }
      const keys = Object.keys(condition);
      if (keys.join(',') !== 'types,default') {
        offenders.push(`${name}: react-native keys are [${keys.join(', ')}], expected [types, default]`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('points react-native.default at src and react-native.types at the built declarations', () => {
    const offenders: string[] = [];
    for (const [name, entry] of subpathEntries) {
      const condition = entry['react-native'];
      if (typeof condition !== 'object' || condition === null) continue;
      const { types, default: def } = condition as { types?: unknown; default?: unknown };

      if (typeof def !== 'string' || !def.startsWith('./src/')) {
        offenders.push(`${name}: react-native.default is ${JSON.stringify(def)}, expected a ./src/ path`);
      }
      if (typeof types !== 'string' || !types.startsWith('./lib/typescript/')) {
        offenders.push(
          `${name}: react-native.types is ${JSON.stringify(types)}, expected a ./lib/typescript/ path`,
        );
      }
    }
    expect(offenders).toEqual([]);
  });

  it('resolves react-native.types to the same declarations as the import condition', () => {
    const offenders: string[] = [];
    for (const [name, entry] of subpathEntries) {
      const condition = entry['react-native'] as { types?: unknown } | undefined;
      const importCondition = entry.import as { types?: unknown } | undefined;
      if (condition?.types !== importCondition?.types) {
        offenders.push(
          `${name}: react-native.types (${String(condition?.types)}) !== import.types (${String(importCondition?.types)})`,
        );
      }
    }
    expect(offenders).toEqual([]);
  });
});

/**
 * The icon PATTERN entry, and the two properties that make it safe.
 *
 * `./icons` is a flat barrel over 461 glyph modules and Metro does not
 * tree-shake, so an app that names one icon through it ships all 461. Measured
 * on a Metro bundle for the 12 `Ri*` names CrowdSource's apps import: 318,869
 * bytes of glyph modules from the barrel against 7,406 by subpath, 365,825
 * bytes of bundle in all (11.0%). Figures and method: `docs/icons.mdx`.
 * `./icons/Ri*` is the same set reachable one module at a time.
 *
 * The prefix is in the PATTERN, not in the `*`, and that is the load-bearing
 * detail. A bare `./icons/*` also matches `index`, and the conditions then
 * disagree about it: the built `icons/remix/index.js` and `index.d.ts` exist while
 * `src/icons/remix/` holds an `index.ts` and no `index.tsx`. Every consumer
 * but Metro would resolve `@oxy.so/bloom/icons/index`; Metro, the one that
 * reads `src/`, would fail — and nothing else in this repo looks at a pattern
 * target, because `existsSync` cannot be asked about a path containing a `*`.
 *
 * `scripts/verify-package.mjs` holds the runtime half of this (every condition
 * expands to the same glyph names inside the real tarball). This file holds
 * the shape.
 */
const ICON_PATTERN = './icons/Ri*';
const ICONS_REMIX_DIR = join(__dirname, '..', 'icons', 'remix');

describe('package.json#exports — the icon subpath pattern', () => {
  const entry = exportsMap[ICON_PATTERN] as ExportEntry | undefined;

  it('declares the pattern', () => {
    expect(entry).toBeDefined();
  });

  it('keeps the flat barrel as an EXACT key, so no existing import moves', () => {
    // An exact key beats a pattern in every resolver that implements
    // `exports`, so `from '@oxy.so/bloom/icons'` is unaffected by the entry
    // above. This is the additive half of the change, and the whole reason it
    // is not a breaking one.
    expect(typeof exportsMap['./icons']).toBe('object');
  });

  it('gives every condition exactly one substitution point', () => {
    const targets: string[] = [];
    const walk = (node: unknown): void => {
      if (typeof node === 'string') return void targets.push(node);
      if (typeof node === 'object' && node !== null) Object.values(node).forEach(walk);
    };
    walk(entry);
    expect(targets.length).toBeGreaterThan(0);
    for (const target of targets) {
      expect(target.split('*')).toHaveLength(2);
    }
  });

  it('cannot express the remix barrel, which ships as .ts and not .tsx', () => {
    expect(existsSync(join(ICONS_REMIX_DIR, 'index.ts'))).toBe(true);
    expect(existsSync(join(ICONS_REMIX_DIR, 'index.tsx'))).toBe(false);
    // `index` does not start with `Ri`, so no substitution produces it.
    expect('index'.startsWith(ICON_PATTERN.slice('./icons/'.length, -1))).toBe(false);
  });

  it('stands for every glyph on disk, and the barrel exports exactly those', () => {
    const onDisk = readdirSync(ICONS_REMIX_DIR)
      .filter((name) => name.endsWith('.tsx'))
      .map((name) => name.slice(0, -'.tsx'.length))
      .sort();

    // The prefix is an invariant of the generated set, not a coincidence: a
    // glyph added under another name would be reachable from the barrel and
    // from nowhere else, which is the asymmetry this whole entry removes.
    expect(onDisk.filter((name) => !name.startsWith('Ri'))).toEqual([]);

    const barrel = readFileSync(join(ICONS_REMIX_DIR, 'index.ts'), 'utf8');
    const exported = [...barrel.matchAll(/export \{ (\w+) \}/g)].map((m) => m[1]).sort();
    expect(exported).toEqual(onDisk);
  });
});

/**
 * The brand marks Remix does not draw (`src/icons/simple-icons/`, Simple Icons,
 * CC0 1.0) get one EXACT key each rather than a `./icons/Si*` pattern — a
 * pattern must clear the generator's 100-match vacuity floor. Exact keys are
 * the shape that can drift: a glyph added to the folder without its key is
 * reachable from the barrel and from nowhere else, the asymmetry the `Ri*`
 * pattern exists to remove.
 */
const ICONS_SIMPLE_DIR = join(__dirname, '..', 'icons', 'simple-icons');

describe('package.json#exports — Simple Icons brand marks', () => {
  const onDisk = readdirSync(ICONS_SIMPLE_DIR)
    .filter((name) => name.endsWith('.tsx'))
    .map((name) => name.slice(0, -'.tsx'.length))
    .sort();

  it('names every file Si-prefixed, so none collides with the Ri* pattern', () => {
    expect(onDisk.length).toBeGreaterThan(0);
    expect(onDisk.filter((name) => !name.startsWith('Si'))).toEqual([]);
  });

  it('gives every glyph on disk an exact subpath, and no key names a missing glyph', () => {
    const keyed = Object.keys(exportsMap)
      .filter((key) => key.startsWith('./icons/Si'))
      .map((key) => key.slice('./icons/'.length))
      .sort();
    expect(keyed).toEqual(onDisk);
  });

  it('barrel-exports exactly the glyphs on disk', () => {
    const barrel = readFileSync(join(ICONS_SIMPLE_DIR, 'index.ts'), 'utf8');
    const exported = [...barrel.matchAll(/export \{ (\w+) \}/g)].map((m) => m[1]).sort();
    expect(exported).toEqual(onDisk);
  });
});

/**
 * `typesVersions` — the same map again, for `moduleResolution: "node"`.
 *
 * node10 ignores `exports` outright. Measured on TypeScript 5.9 against a
 * fixture, `@oxy.so/bloom/icons`, `@oxy.so/bloom/theme` and
 * `@oxy.so/bloom/button` each reported TS2307 under it while resolving
 * cleanly under `node16` and `bundler` — so no Bloom subpath typechecked for
 * a consumer on that setting, and the compiler's own hint was the only thing
 * that said so.
 *
 * Emitted for every subpath rather than only the icons pattern: the
 * alternative is `@oxy.so/bloom/icons/RiAddFill` typechecking while the barrel
 * beside it does not.
 *
 * TypeScript does NOT consult this field when the package has `exports` and
 * resolution is `node16`/`nodenext`/`bundler`, so it cannot change a modern
 * answer — which is why the equality with `import.types` below is the property
 * worth holding: the two maps must never diverge in what they claim.
 */
describe('package.json#typesVersions — legacy node10 resolution', () => {
  const typesVersions = (
    JSON.parse(readFileSync(PKG_PATH, 'utf8')) as {
      typesVersions?: Record<string, Record<string, string[]>>;
    }
  ).typesVersions;
  const map = typesVersions?.['*'] ?? {};

  it('applies to every TypeScript version', () => {
    expect(Object.keys(typesVersions ?? {})).toEqual(['*']);
  });

  it('covers every subpath but the root, which the `types` field already answers', () => {
    const declared = subpathEntries.map(([name]) => name).filter((name) => name !== '.');
    const covered = Object.keys(map).map((name) => `./${name}`);
    expect(covered.sort()).toEqual(declared.sort());
    expect(map['.']).toBeUndefined();
  });

  it('points at the same declarations as the import condition', () => {
    const offenders: string[] = [];
    for (const [name, entry] of subpathEntries) {
      if (name === '.') continue;
      const importTypes = (entry.import as { types?: string } | undefined)?.types;
      const legacy = map[name.slice(2)];
      if (legacy?.length !== 1 || legacy[0] !== importTypes) {
        offenders.push(`${name}: typesVersions ${JSON.stringify(legacy)} !== import.types ${String(importTypes)}`);
      }
    }
    expect(offenders).toEqual([]);
  });
});
