import { readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The `react-native` export condition must stay SPLIT into `types` + `default`.
 *
 * Metro compiles Bloom from source, so `default` points at `src/`. TypeScript
 * honours `react-native` as well (expo/tsconfig.base sets
 * `customConditions: ["react-native"]`), and if the condition were a bare
 * string every native-targeted consumer would type-check Bloom's own `.tsx`
 * files — pulling `react-dom` (from the web forks) and optional peers like
 * `expo-haptics` / `@react-native-community/netinfo` into a program that never
 * declared them. Measured against a consumer fixture with no
 * `@types/react-dom`, the string form produces TS7016 on
 * `src/portal/index.web.tsx`, TS2307 on `src/hooks/useHaptics.tsx` and
 * `src/connection-status/index.tsx`, plus a nativewind TS2769 on
 * `src/dialog/DialogHeader.tsx`. `skipLibCheck` cannot suppress any of them —
 * a `.tsx` is not a declaration file.
 *
 * Splitting the condition means tsc asks for `types` and gets the built
 * declarations, while Metro (which never requests `types`) still falls through
 * to `default` and bundles source. Verified end to end with a real
 * `expo export --platform ios`.
 *
 * `package.json#exports` is generated by `scripts/generate-platform-exports.mjs`
 * — fix a failure there, never by hand-editing `package.json`.
 */

type ExportEntry = Record<string, unknown>;

// Read rather than `import` the manifest: tsconfig pins `rootDir` to `src`, so
// a JSON import from outside it would drag package.json into the build program.
const PKG_PATH = join(__dirname, '..', '..', 'package.json');
const pkg = JSON.parse(readFileSync(PKG_PATH, 'utf8')) as {
  exports: Record<string, ExportEntry | string>;
};
const exportsMap = pkg.exports;

/** Non-subpath entries that are legitimately plain strings (static assets). */
const STRING_ENTRIES = [
  './design-tokens/theme.css',
  './design-tokens/tokens.json',
  './package.json',
];

/**
 * Vacuity floor. `SUBPATHS` in the generator is 86 entries today; a traversal
 * bug that silently found none must not read as a pass.
 */
const MIN_SUBPATHS = 80;

const subpathEntries = Object.entries(exportsMap).filter(
  (entry): entry is [string, ExportEntry] => typeof entry[1] !== 'string',
);

describe('package.json#exports — react-native condition', () => {
  it(`declares at least ${MIN_SUBPATHS} conditional subpaths`, () => {
    expect(subpathEntries.length).toBeGreaterThanOrEqual(MIN_SUBPATHS);
  });

  it('exposes only the known static assets as string exports', () => {
    const strings = Object.entries(exportsMap)
      .filter(([, value]) => typeof value === 'string')
      .map(([name]) => name);
    expect(strings.sort()).toEqual([...STRING_ENTRIES].sort());
  });

  it('splits every react-native condition into types + default, in that order', () => {
    const offenders: string[] = [];
    for (const [name, entry] of subpathEntries) {
      const condition = entry['react-native'];
      if (typeof condition !== 'object' || condition === null) {
        offenders.push(`${name}: react-native is ${JSON.stringify(condition)}, expected an object`);
        continue;
      }
      const keys = Object.keys(condition);
      if (keys.join(',') !== 'types,default') {
        offenders.push(`${name}: react-native keys are [${keys.join(', ')}], expected [types, default]`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('points react-native.default at src and react-native.types at the built declarations', () => {
    const offenders: string[] = [];
    for (const [name, entry] of subpathEntries) {
      const condition = entry['react-native'];
      if (typeof condition !== 'object' || condition === null) continue;
      const { types, default: def } = condition as { types?: unknown; default?: unknown };

      if (typeof def !== 'string' || !def.startsWith('./src/')) {
        offenders.push(`${name}: react-native.default is ${JSON.stringify(def)}, expected a ./src/ path`);
      }
      if (typeof types !== 'string' || !types.startsWith('./lib/typescript/')) {
        offenders.push(
          `${name}: react-native.types is ${JSON.stringify(types)}, expected a ./lib/typescript/ path`,
        );
      }
    }
    expect(offenders).toEqual([]);
  });

  it('resolves react-native.types to the same declarations as the import condition', () => {
    const offenders: string[] = [];
    for (const [name, entry] of subpathEntries) {
      const condition = entry['react-native'] as { types?: unknown } | undefined;
      const importCondition = entry.import as { types?: unknown } | undefined;
      if (condition?.types !== importCondition?.types) {
        offenders.push(
          `${name}: react-native.types (${String(condition?.types)}) !== import.types (${String(importCondition?.types)})`,
        );
      }
    }
    expect(offenders).toEqual([]);
  });
});
