// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/content-panel/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export {
  GUTTER_MASK_SPREAD,
  PANEL_TOP_INSET,
  PANEL_BOTTOM_INSET,
  ContentPanel,
} from './ContentPanel.web';
export type { ContentPanelChrome, ContentPanelFramedBreakpoint, ContentPanelProps } from './types';
