// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/theme/seed-scope/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { BloomSeedScope } from './SeedScope.web';
export type { BloomSeedScopeProps } from './SeedScope.web';
