import type { SchemeVariant } from './color-engine';

export type AppColorName =
  | 'teal'
  | 'blue'
  | 'green'
  | 'yellow'
  | 'red'
  | 'purple'
  | 'pink'
  | 'sky'
  | 'orange'
  | 'mint'
  | 'oxy'
  | 'faircoin'
  | 'pumpkin'
  | 'gray'
  | 'brown'
  | 'peach'
  | 'rose'
  | 'mono';

/**
 * A single colour preset: a brand SEED colour plus the tonal scheme variant to
 * derive its full role set with.
 *
 * Every preset's palette is now GENERATED by Bloom's dependency-free colour
 * engine (`color-engine/`) from this seed — no hand-authored HSL triples. The
 * engine's `generateRoleColors({ seed, variant, isDark })` yields the full
 * Material-3 role set for light and dark; `getPresetVars` (in `preset-vars.ts`)
 * maps those roles onto Bloom's canonical token names. A user-picked colour
 * flows through the identical path — a preset is just a fixed seed.
 */
/**
 * Why a preset is not offered to every user. Absent means it is.
 *
 * The two are NOT interchangeable and must not collapse back into one list: a
 * `handle` preset belongs to a specific account and cannot be bought, while a
 * `premium` one is exactly what is bought. Conflating them is how the picker
 * came to offer both of Oxy's reserved brand colours to everybody.
 */
export type ColorPresetGate =
  /** Reserved for the account whose brand it is — not purchasable. */
  | 'handle'
  /** Sold with a subscription. */
  | 'premium';

export interface AppColorPreset {
  name: AppColorName;
  /** The brand seed colour, `#rrggbb`. Also the value the colour picker matches. */
  hex: string;
  /** The tonal scheme variant the engine derives roles with. */
  variant: SchemeVariant;
  /**
   * Optional explicit secondary-accent seed, `#rrggbb`. When set, the secondary
   * palette is PINNED to this brand colour (hue + chroma preserved; M3 role tones
   * still apply) instead of the derived hue-rotation of {@link AppColorPreset.hex}.
   * Bloom's built-in presets do NOT set this, so their generated output is
   * unchanged; a consumer brand with a distinct accent (blue primary + yellow
   * secondary) sets it to pin its real accent family.
   */
  secondaryHex?: string;
  /**
   * Optional explicit tertiary-accent seed, `#rrggbb`. Same semantics as
   * {@link AppColorPreset.secondaryHex} for the tertiary palette.
   */
  tertiaryHex?: string;
  /**
   * Who may pick this preset. Absent = everyone. Bloom only DECLARES the gate;
   * whether a given viewer satisfies it is the consuming app's question, since
   * only the app knows who is signed in and what they pay for.
   */
  gate?: ColorPresetGate;
}

/**
 * Historically each preset carried a full light/dark map of raw HSL triples.
 * That map is gone — the engine derives every role from {@link AppColorPreset.hex}.
 * The type alias is retained for the public `PresetTokens` export shape (the
 * resolved `--token -> value` record that `getPresetVars` produces).
 */
export type PresetTokens = Record<string, string>;

export const APP_COLOR_NAMES: readonly AppColorName[] = ['teal', 'blue', 'green', 'yellow', 'red', 'purple', 'pink', 'sky', 'orange', 'mint', 'oxy', 'faircoin', 'pumpkin', 'gray', 'brown', 'peach', 'rose', 'mono'];

export const HEX_TO_APP_COLOR: Record<string, AppColorName> = {
  '#005c67': 'teal',
  '#0085fe': 'blue',
  '#10b981': 'green',
  '#fcdc00': 'yellow',
  '#ef4444': 'red',
  '#b866ff': 'purple',
  '#ff3c7f': 'pink',
  '#03a9f4': 'sky',
  '#ff5722': 'orange',
  '#14b8a6': 'mint',
  '#c46ede': 'oxy',
  '#9ffb50': 'faircoin',
  '#ff9800': 'pumpkin',
  '#607d8b': 'gray',
  '#813519': 'brown',
  '#ffb28d': 'peach',
  '#fcaffe': 'rose',
  '#000000': 'mono',
};

export function hexToAppColorName(hex: string): AppColorName {
  return HEX_TO_APP_COLOR[hex.toLowerCase()] ?? 'teal';
}

/**
 * The 13 named presets, each a brand seed + scheme variant. The engine derives
 * the full role set (light + dark) from the seed. Seeds are the brand hex of
 * each preset; `oxy` reads most faithfully as `vibrant`, everything else keeps a
 * bold `vibrant` derivation to match the prior saturated palette.
 */
export const APP_COLOR_PRESETS: Record<AppColorName, AppColorPreset> = {
  teal: { name: 'teal', hex: '#005c67', variant: 'vivid' },
  blue: { name: 'blue', hex: '#0085fe', variant: 'vivid' },
  green: { name: 'green', hex: '#10b981', variant: 'vivid' },
  yellow: { name: 'yellow', hex: '#fcdc00', variant: 'vivid' },
  red: { name: 'red', hex: '#ef4444', variant: 'vivid' },
  purple: { name: 'purple', hex: '#b866ff', variant: 'vivid' },
  pink: { name: 'pink', hex: '#ff3c7f', variant: 'vivid' },
  sky: { name: 'sky', hex: '#03a9f4', variant: 'vivid' },
  // Deliberately NOT Tailwind's orange-500 (`#f97316`). That seed sits at HCT hue
  // 46, which reads as orange only because it is also light: at hue 46 the sRGB
  // gamut allows a chroma of just 62 at the tones a white label needs (<= 49), so
  // the brand fill resolved to `rgb(177 76 0)` — a brown. Hue 34 carries a chroma
  // of 84 at that same tone, with the same white label and the same contrast
  // headroom, so the fill reads as orange instead of paying for the hue twice.
  orange: { name: 'orange', hex: '#ff5722', variant: 'vivid' },
  mint: { name: 'mint', hex: '#14b8a6', variant: 'vivid' },
  oxy: { name: 'oxy', hex: '#c46ede', variant: 'vivid', gate: 'handle' },
  faircoin: { name: 'faircoin', hex: '#9ffb50', variant: 'vivid', gate: 'handle' },
  pumpkin: { name: 'pumpkin', hex: '#ff9800', variant: 'vivid' },
  gray: { name: 'gray', hex: '#607d8b', variant: 'vivid' },
  brown: { name: 'brown', hex: '#813519', variant: 'vivid' },
  peach: { name: 'peach', hex: '#ffb28d', variant: 'vivid' },
  rose: { name: 'rose', hex: '#fcaffe', variant: 'vivid' },
  /**
   * No colour at all — the black-and-white theme. Its seed carries zero chroma,
   * which is the whole mechanism: the policy derives a greyscale palette from any
   * seed with none, so a user who picks a grey in the colour wheel lands here too
   * rather than on a nearly-grey approximation.
   */
  mono: { name: 'mono', hex: '#000000', variant: 'monochrome', gate: 'premium' },
};

/**
 * The three gate groups, DERIVED from the presets rather than listed again, so a
 * preset cannot be gated in one place and offered in another. Together they
 * partition {@link APP_COLOR_NAMES} exactly — asserted in
 * `__tests__/color-preset-gates.test.ts`, since a preset silently missing from
 * every group would simply vanish from a picker with no error anywhere.
 *
 * A consumer builds its visible list from these; it must NOT start from
 * `APP_COLOR_NAMES` and add the unlocked ones, which yields the gated presets to
 * everybody and duplicates whatever the viewer did unlock.
 */
const namesGatedBy = (gate: ColorPresetGate | undefined): readonly AppColorName[] =>
  APP_COLOR_NAMES.filter((name) => APP_COLOR_PRESETS[name].gate === gate);

/** Available to every user, signed in or not. */
export const FREE_COLOR_NAMES: readonly AppColorName[] = namesGatedBy(undefined);

/** Reserved for the account whose brand it is (`oxy`, `faircoin`) — not for sale. */
export const HANDLE_COLOR_NAMES: readonly AppColorName[] = namesGatedBy('handle');

/** Sold with a subscription. */
export const PREMIUM_COLOR_NAMES: readonly AppColorName[] = namesGatedBy('premium');
