import type { SchemeVariant } from './color-engine';

export type AppColorName =
  | 'teal'
  | 'blue'
  | 'green'
  | 'amber'
  | 'yellow'
  | 'red'
  | 'purple'
  | 'pink'
  | 'sky'
  | 'orange'
  | 'mint'
  | 'oxy'
  | 'faircoin';

/**
 * A single colour preset: a brand SEED colour plus the tonal scheme variant to
 * derive its full role set with.
 *
 * Every preset's palette is now GENERATED by Bloom's dependency-free colour
 * engine (`color-engine/`) from this seed — no hand-authored HSL triples. The
 * engine's `generateRoleColors({ seed, variant, isDark })` yields the full
 * Material-3 role set for light and dark; `getPresetVars` (in `preset-vars.ts`)
 * maps those roles onto Bloom's canonical token names. A user-picked colour
 * flows through the identical path — a preset is just a fixed seed.
 */
export interface AppColorPreset {
  name: AppColorName;
  /** The brand seed colour, `#rrggbb`. Also the value the colour picker matches. */
  hex: string;
  /** The tonal scheme variant the engine derives roles with. */
  variant: SchemeVariant;
  /**
   * Optional explicit secondary-accent seed, `#rrggbb`. When set, the secondary
   * palette is PINNED to this brand colour (hue + chroma preserved; M3 role tones
   * still apply) instead of the derived hue-rotation of {@link AppColorPreset.hex}.
   * Bloom's built-in presets do NOT set this, so their generated output is
   * unchanged; a consumer brand with a distinct accent (blue primary + yellow
   * secondary) sets it to pin its real accent family.
   */
  secondaryHex?: string;
  /**
   * Optional explicit tertiary-accent seed, `#rrggbb`. Same semantics as
   * {@link AppColorPreset.secondaryHex} for the tertiary palette.
   */
  tertiaryHex?: string;
}

/**
 * Historically each preset carried a full light/dark map of raw HSL triples.
 * That map is gone — the engine derives every role from {@link AppColorPreset.hex}.
 * The type alias is retained for the public `PresetTokens` export shape (the
 * resolved `--token -> value` record that `getPresetVars` produces).
 */
export type PresetTokens = Record<string, string>;

export const APP_COLOR_NAMES: readonly AppColorName[] = ['teal', 'blue', 'green', 'amber', 'yellow', 'red', 'purple', 'pink', 'sky', 'orange', 'mint', 'oxy', 'faircoin'];

/** Premium-exclusive presets, hidden from the standard color picker. */
export const PREMIUM_COLOR_NAMES: readonly AppColorName[] = ['oxy', 'faircoin'];

export const HEX_TO_APP_COLOR: Record<string, AppColorName> = {
  '#005c67': 'teal',
  '#1d9bf0': 'blue',
  '#10b981': 'green',
  '#f59e0b': 'amber',
  '#ffc300': 'yellow',
  '#ef4444': 'red',
  '#8b5cf6': 'purple',
  '#ec4899': 'pink',
  '#0ea5e9': 'sky',
  '#f97316': 'orange',
  '#14b8a6': 'mint',
  '#c46ede': 'oxy',
  '#9ffb50': 'faircoin',
};

export function hexToAppColorName(hex: string): AppColorName {
  return HEX_TO_APP_COLOR[hex.toLowerCase()] ?? 'teal';
}

/**
 * The 13 named presets, each a brand seed + scheme variant. The engine derives
 * the full role set (light + dark) from the seed. Seeds are the brand hex of
 * each preset; `oxy` reads most faithfully as `vibrant`, everything else keeps a
 * bold `vibrant` derivation to match the prior saturated palette.
 */
export const APP_COLOR_PRESETS: Record<AppColorName, AppColorPreset> = {
  teal: { name: 'teal', hex: '#005c67', variant: 'vivid' },
  blue: { name: 'blue', hex: '#1d9bf0', variant: 'vivid' },
  green: { name: 'green', hex: '#10b981', variant: 'vivid' },
  amber: { name: 'amber', hex: '#f59e0b', variant: 'vivid' },
  yellow: { name: 'yellow', hex: '#ffc300', variant: 'vivid' },
  red: { name: 'red', hex: '#ef4444', variant: 'vivid' },
  purple: { name: 'purple', hex: '#8b5cf6', variant: 'vivid' },
  pink: { name: 'pink', hex: '#ec4899', variant: 'vivid' },
  sky: { name: 'sky', hex: '#0ea5e9', variant: 'vivid' },
  orange: { name: 'orange', hex: '#f97316', variant: 'vivid' },
  mint: { name: 'mint', hex: '#14b8a6', variant: 'vivid' },
  oxy: { name: 'oxy', hex: '#c46ede', variant: 'vivid' },
  faircoin: { name: 'faircoin', hex: '#9ffb50', variant: 'vivid' },
};
