// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/sticker/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Sticker } from './Sticker.web';
export { provideLottiePlayer, resetLottiePlayer } from './lottie-module.web';
export type { LottiePlayerProps, StickerProps } from './types';
