// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/app-shell/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

import { createAppShell } from './AppShell';
import { BottomBar } from '../bottom-bar/index.web';
import { Fab } from '../fab/index.web';
export const AppShell = createAppShell(BottomBar, Fab);
export { AppShellHeader } from './AppShellHeader';
export { NotificationBell } from './NotificationBell';
export { ProOfferCard } from './ProOfferCard';

export type {
  AppShellNavigationPlacement,
  AppShellNavigationItem,
  AppShellHeaderProps,
  AppShellProps,
  NotificationBellProps,
  ProOfferCardProps,
} from './types';
