// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/app-shell/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

import { createAppShell } from './AppShell';
import { BottomBar } from '../bottom-bar/index.web';
import { Fab } from '../fab/index.web';
import { ContentPanel } from '../content-panel/index.web';
import { BloomColorScope } from '../theme/color-scope/index.web';
export const AppShell = createAppShell(BottomBar, Fab, ContentPanel, BloomColorScope);
export { AppShellHeader } from './AppShellHeader';
export { AppShellMenuButton } from './AppShellMenuButton';
export { APP_SHELL_DEFAULTS } from './constants';
export { useAppShell } from './context';
export type { AppShellContextValue } from './context';
export { NotificationBell } from './NotificationBell';
export { ProOfferCard } from './ProOfferCard';

export type {
  AppShellNavigationPlacement,
  AppShellNavigationItem,
  AppShellBarVisibility,
  AppShellBreakpoint,
  AppShellDrawer,
  AppShellPane,
  AppShellScroll,
  AppShellVariant,
  AppShellHeaderProps,
  AppShellMenuButtonProps,
  AppShellProps,
  NotificationBellProps,
  ProOfferCardProps,
} from './types';
