// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/motion/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ScaleAndFadeIn, ScaleAndFadeOut, ShrinkAndPop } from './motion.web';
export { ScreenTransition } from './ScreenTransition';
export type { ScreenTransitionProps, ScreenTransitionDirection } from './types';
