// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/viewport/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ViewportProvider } from './ViewportProvider';
export { useViewportBinding } from './use-viewport-binding';
export { useInView } from './use-in-view.web';
export type {
  ViewportProviderProps,
  ViewportBindingOptions,
  InViewOptions,
  VisibilityHandle,
  ViewportHandle,
} from './types';
