// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/button/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { Button } from './Button.web';
export { CloseButton } from './CloseButton';
export type { ButtonProps, ButtonSize, ButtonIconComponent, CloseButtonProps } from './types';
