/**
 * Generate the static `src/design-tokens/theme.css` artifact from the SAME
 * source as `bloomThemeCss()` so the JS token block and the shippable CSS
 * file can never drift.
 *
 * Tailwind v4 / NativeWind CSS-first consumers `@import` this file instead of
 * pasting the `@theme { … }` body into their own `global.css`:
 *
 *   @import "@oxyhq/bloom/design-tokens/theme.css";
 *
 * The checked-in output is verified in `src/__tests__/design-tokens.test.ts`,
 * which asserts the `@theme` block in this file equals `bloomThemeBlock()`.
 *
 * Run with bun (imports the TS source directly):
 *   bun run generate:theme-css
 *
 * Wired as a `prebuild` step so `bun run build` always regenerates it.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bloomThemeBlock } from '../src/design-tokens/theme-css';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..');
const OUT_PATH = join(REPO_ROOT, 'src', 'design-tokens', 'theme.css');

const HEADER = [
  '/*',
  ' * AUTO-GENERATED by scripts/generate-theme-css.ts — DO NOT EDIT.',
  ' * Source of truth: bloomThemeCss() in src/design-tokens/theme-css.ts.',
  ' * Re-run `bun run generate:theme-css` (or any `bun run build`) after',
  ' * changing any design token.',
  ' */',
].join('\n');

const css = `${HEADER}\n\n${bloomThemeBlock()}\n`;

writeFileSync(OUT_PATH, css);
console.log(
  `[generate-theme-css] wrote ${relative(REPO_ROOT, OUT_PATH)} (${css.length} bytes)`,
);
