// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/agent-chat/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export {
  AgentChat,
  AgentChatActions,
  AgentChatComposer,
  AgentChatHistory,
} from './AgentChat.web';
export { AgentChatMessage } from './AgentChatMessage';
export type {
  AgentChatAccount,
  AgentChatAccountMenuItem,
  AgentChatActionsLabels,
  AgentChatActionsProps,
  AgentChatComposerLabels,
  AgentChatComposerProps,
  AgentChatHistoryLabels,
  AgentChatHistoryProps,
  AgentChatLabels,
  AgentChatMessageData,
  AgentChatMessageLabels,
  AgentChatMessageProps,
  AgentChatProps,
  AgentChatStatus,
  AgentChatThread,
  AgentChatUsageRow,
} from './types';
