// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

// WHAT BELONGS ON THIS BARREL — the rule, so the gaps stop being folklore.
//
// A family is HERE unless one of two things is true:
//
//  1. Importing it would add a package to this barrel's module graph. Metro
//     does not tree-shake, so `import { Button } from '@oxy.so/bloom'` links
//     everything this file can reach — and an unmet REQUIRED peer is a build
//     failure, not a degradation. Measured today exactly three families fail
//     this, and each is reachable only through its own subpath:
//       · `./tab-bar` — statically imports `expo-glass-effect` + `expo-symbols`
//         from its `.native` files. Both ship Apple-only native modules, and the
//         "a consumer that never imports @oxy.so/bloom/tab-bar never reaches
//         them" rule in AGENTS.md is true only while this stays off the barrel.
//       · `./provider` remains an explicit subpath. BloomProvider is universal;
//         router restoration is supplied explicitly.
//       · `./zoomable-media-gallery` and `./media-flight` — both reach
//         `expo-image` through the shared `media-flight/MediaSurface`.
//     Gate: `src/__tests__/root-barrel-graph.test.ts`.
//
//  2. Its exports are generic, collision-prone names. Those come in as a
//     NAMESPACE (the same rule that makes `Icons`/`Skeleton`/`Grid` namespaces),
//     never as loose top-level verbs.
//
// Everything else is here, including the pure-JS families that were absent for
// no recorded reason (`image-resolver`, `image-aspect-ratio-cache`, `scroll`,
// `overlay`, `content-panel`, `list`, `progressive-blur`, `connection-status`).

// Theme
export * from './theme/index.web';

// Styles & Utilities
export { atoms, flatten, Z_INDEX } from './styles';
export type { ViewStyleProp, TextStyleProp } from './styles';
export * as tokens from './styles/tokens';
export { web, native, ios, android, platform, select } from './styles/platform';

// Design tokens (Oxy Unified Design Language) — semantic Tailwind/NativeWind
// vocabulary. The Tailwind preset is consumed from `@oxy.so/bloom/tailwind-preset`
// in a config file; these named exports cover programmatic/runtime use.
export {
  bloomTailwindPreset,
  bloomThemeCss,
  bloomThemeBlock,
  FILL_ROLES,
  TEXT_ROLES,
  ACCENT_TEXT_ROLES,
  BORDER_ROLES,
  SPACING,
  RADIUS,
  BORDER_WIDTH,
  TYPOGRAPHY,
  FONT_FAMILY_VARS,
  SHADOW_BOX,
  bloomShadowStyle,
} from './design-tokens';
export type {
  TailwindPreset,
  TailwindPresetThemeExtend,
  FillRole,
  TextRole,
  AccentTextRole,
  BorderRole,
  TypeRole,
  TypeRoleName,
  ShadowRole,
} from './design-tokens';

// Hooks — through the family's own barrel, not eight deep paths into it.
// Reaching THROUGH a family is how `@oxy.so/bloom` and `@oxy.so/bloom/hooks`
// came to disagree about what the hooks family is: `useInteractionStates`,
// `usePressAnimation` and `mergeRefs` were on the subpath and not here, for no
// reason anyone had decided.
export * from './hooks';

// Icons
export * as Icons from './icons';
export { type Props as IconProps, sizes as iconSizes, useCommonSVGProps } from './icons/shared';
export type { BloomIconComponent } from './icons/icon-component';

// App-wide plumbing (pure JS — no peer beyond what this barrel already links)
export { ImageResolverProvider, useImageResolver, isImageUrl } from './image-resolver';
export type { ImageResolver } from './image-resolver';
// A namespace, not seven loose verbs: `getAspectRatio`/`setAspectRatio`/
// `hasAspectRatio` are exactly the collision-prone shape the namespace rule
// covers.
export * as ImageAspectRatio from './image-aspect-ratio-cache';
export { ScrollRestorationProvider, useScrollRestoration } from './scroll/index.web';
export type {
  ScreenFocusEffect,
  ScrollableHandle,
  ScrollRestorationBinding,
  ScrollRestorationProviderProps,
  ScrollRestorationTarget,
  ScrollRouterAdapter,
  UseScrollRestorationOptions,
} from './scroll/index.web';
export { ConnectionStatusToasts } from './connection-status/index.web';
export type { ConnectionStatusToastsProps } from './connection-status/index.web';

// Core components
export * from './portal/index.web';
// Overlay plumbing — the ONE way a portaled surface takes its place in the
// stack (`src/overlay/stack.ts`) and draws its press-to-dismiss dim.
export {
  OverlayRoot,
  Backdrop,
  useOverlayLayer,
  useOverlayLayerContext,
  layerForRank,
  BACKDROP_BLUR_INTENSITY,
  BACKDROP_DIM_OPACITY,
  OVERLAY_STACK_BAND,
  OVERLAY_STACK_BASE,
  OVERLAY_STACK_MAX_RANK,
  TOAST_LAYER_Z,
} from './overlay';
export type { OverlayRootProps, BackdropProps, OverlayLayer } from './overlay';
export {
  Dialog,
  useDialogContext,
  useDialogControl,
  useDialogHeader,
} from './dialog/index.web';
export type {
  DialogAction,
  DialogActionColor,
  DialogContextProps,
  DialogControlProps,
  DialogHeaderConfig,
  DialogInset,
  DialogPlacement,
  DialogProps,
  ResponsiveDialogPlacement,
} from './dialog/index.web';
// Surface stack — the ONE coordinated overlay system, and the ONE imperative
// overlay API. `alert()` and `confirm()` present into it (they used to be two
// separate FIFO queues with hosts of their own); `prompt` and the rest of the
// stack controls are named exports of `@oxy.so/bloom/surfaces`.
export { surfaces, alert, confirm, SurfaceProvider, SurfaceHost, useSurface } from './surfaces/index.web';
export type {
  SurfacePresentation,
  PresentOptions,
  SurfaceControls,
  SurfaceRenderFn,
  SurfaceStatus,
  SurfaceEntry,
  AlertButton,
  AlertButtonStyle,
  SurfaceConfirmOptions,
  SurfacePromptOptions,
} from './surfaces/index.web';
export * from './appearance';
export * from './screen';
export * from './bottom-bar/index.web';
export * from './button/index.web';
export * from './button-group';
export * from './control-surface';
export {
  EDGE_GAP,
  windowEdgeGap,
  BottomEdgeProvider,
  useBottomEdgeInset,
  useClaimBottomEdge,
  TopEdgeProvider,
  useClaimTopEdge,
  useTopEdgeInset,
  ScrollOffsetProvider,
  useScrollOffset,
  ScreenScope,
} from './layout';
export { Fab } from './fab/index.web';
export type { FabProps, FabVariant, FabSize, FabPlacement, FabMinimizeBehavior } from './fab/index.web';
export { FrostedIconButton } from './frosted-icon-button/index.web';
export type { FrostedIconButtonProps, FrostedIconButtonSize } from './frosted-icon-button/index.web';
export * from './divider';
export * from './breadcrumb';
export * from './pagination';
export * from './agent-limits-card';
export { Carousel, CarouselItem } from './carousel';
export type { CarouselProps, CarouselItemProps } from './carousel';
export { FileUpload, formatFileSize } from './file-upload';
export type { FileUploadFile, FileUploadLabels, FileUploadProps } from './file-upload';
export { SocialButton, SOCIAL_PROVIDERS } from './social-button';
export type { SocialBrand, SocialBrandConfig, SocialButtonAppearance, SocialButtonProps, SocialButtonSize, SocialProvider } from './social-button';
export * from './notification';
export * from './announcement';
export * from './data-table';
export * from './chart-cards';
export * from './calendar';
export * from './stat-cards';
export * from './recent-hires-card';
export * from './ai-profile-card';
export * from './important-alerts-card';
export * from './patient-info-card';
export * from './sidebar';
export * from './app-shell/index.web';
export * from './page-header';
export * from './notification-center';
export * from './theme-toggle';
export * from './settings-modal';
export * from './auth-card';
export * from './agent-thinking';
export * from './agent-log';
export * from './agent-progress';
export * from './composer-loader/index.web';
export * from './composer-panel/index.web';
export * from './questionnaire';
export * from './web-search';
export * from './task-list';
export * from './agent-chat/index.web';
export * from './ai-chat/index.web';
export * from './radio-indicator';
export { ErrorBoundary } from './error-boundary';
export type {
  ErrorBoundaryProps,
  ErrorBoundaryFallback,
  ErrorBoundaryFallbackContext,
} from './error-boundary';
export * from './avatar';
export { AvatarGroup } from './avatar-group/index.web';
export type { AvatarGroupProps, AvatarGroupItem } from './avatar-group/index.web';
export { UserHoverCard } from './user-hover-card';
export type { UserHoverCardProps, UserHoverCardStat } from './user-hover-card';
export * from './loading/index.web';
export * from './switch';
// `ToastOutlet` is a required app-root mount, like `SurfaceHost`. The full
// engine surface lives at `@oxy.so/bloom/toast`.
export { toast, ToastOutlet } from './toast';
export type { ToastFn, ToastOptions, ToastType } from './toast';

// Typography
export * as Typography from './typography';

// Layout primitives
export * as Skeleton from './skeleton';
export * as Grid from './grid';
export { Fill } from './fill';
export { MediaInsetBorder } from './media-inset-border';
export type { MediaInsetBorderProps } from './media-inset-border';
export { IconCircle } from './icon-circle';
// Nothing to show, said once: a glyph or an illustration, a title, a line, and
// up to two actions. A base family — twelve components had each drawn their own
// version of this block, at five paddings and under six different prop names.
export { EmptyState } from './empty-state';
export { EMPTY_STATE_ACTION_GAP, EMPTY_STATE_GEOMETRY, joinEmptyStateName, resolveEmptyStatePaint } from './empty-state';
export type {
  EmptyStateAction,
  EmptyStateGeometry,
  EmptyStateMedia,
  EmptyStatePaint,
  EmptyStateProps,
  EmptyStateVariant,
} from './empty-state';
export { ConnectionDots } from './connection-dots/index.web';
export type { ConnectionDotsProps } from './connection-dots/index.web';
export {
  ContentPanel,
  GUTTER_MASK_SPREAD,
  PANEL_TOP_INSET,
  PANEL_BOTTOM_INSET,
} from './content-panel/index.web';
export type { ContentPanelProps, ContentPanelFramedBreakpoint } from './content-panel/index.web';
export { ProgressiveBlur } from './progressive-blur/index.web';
export type { ProgressiveBlurProps } from './progressive-blur/index.web';
export { VirtualList } from './list/index.web';
export type {
  VirtualListHandle,
  VirtualListProps,
  VirtualListRenderItem,
  VirtualListRenderItemInfo,
  VirtualListSlot,
} from './list/index.web';
export { Rail } from './rail';
export type { RailItem, RailProps } from './rail';

// Interaction primitives
export { PressableScale } from './pressable-scale';
export type { PressableScaleProps } from './pressable-scale';
export { SubtleHover } from './subtle-hover';
export type { SubtleHoverProps } from './subtle-hover';

// Motion presets (Reanimated enter/exit + directional screen transition)
export { ScaleAndFadeIn, ScaleAndFadeOut, ShrinkAndPop, ScreenTransition } from './motion/index.web';
export type { ScreenTransitionProps, ScreenTransitionDirection } from './motion/index.web';
export { AnimatedCheck } from './animated-check';
export type { AnimatedCheckProps, AnimatedCheckRef } from './animated-check';

// Form components
export * from './text-field';
export * from './segmented-control';
export * from './textarea';
export * from './input-otp';
export * from './table';
export * from './date-picker';
export { Search } from './search';
export { Label } from './label';
export type { LabelProps } from './label';
export { Field, useFieldControl, useFieldMembership } from './field';
export type {
  FieldControlValue,
  FieldLabelPlacement,
  FieldMembership,
  FieldMembershipInput,
  FieldProps,
} from './field';
export { InputGroup, InputGroupAddon } from './input-group';
export type { InputGroupProps, InputGroupAddonProps } from './input-group';
export { RangeSlider, Slider } from './slider';
export type { RangeSliderProps, SliderProps } from './slider';
export { Stepper, StepperRow } from './stepper';
export type { StepperProps, StepperRowProps, StepperSize } from './stepper';

// Bottom sheet
export { BottomSheet } from './bottom-sheet/index.web';
export type { BottomSheetRef, BottomSheetProps } from './bottom-sheet/index.web';

// Data display
export * from './card';
export * from './badge';
export { Rating, RatingBar, RatingInput } from './rating';
export type {
  RatingBarProps,
  RatingCountStyle,
  RatingInputProps,
  RatingInputSize,
  RatingProps,
  RatingSize,
} from './rating';
export {
  ExplicitBadge,
  formatDuration,
  LikeButton,
  NowPlayingIndicator,
  PlayButton,
  PlaybackProgress,
  VolumeControl,
} from './media-controls';
export type {
  ExplicitBadgeProps,
  ExplicitBadgeSize,
  LikeButtonProps,
  LikeButtonSize,
  NowPlayingIndicatorProps,
  PlayButtonProps,
  PlayButtonSize,
  PlayButtonVariant,
  PlaybackProgressProps,
  PlaybackProgressTimes,
  VolumeControlProps,
  VolumeSliderVisibility,
} from './media-controls';
export {
  AvatarPresence,
  formatUnreadCount,
  MessageStatus,
  PresenceDot,
  StoryRing,
  TypingDots,
  UnreadBadge,
} from './chat-indicators';
export type {
  AvatarPresenceProps,
  MessageDeliveryStatus,
  MessageStatusProps,
  MessageStatusSize,
  PresenceDotProps,
  PresenceDotSize,
  PresenceStatus,
  StoryRingProps,
  StoryRingState,
  TypingDotsProps,
  UnreadBadgeProps,
  UnreadBadgeSize,
  ChatIconComponent,
} from './chat-indicators';
export {
  CallControlButton,
  CallControls,
  CallHistoryList,
  CallHistoryRow,
  CallMinimisedPill,
  CallScreen,
  GroupCallBar,
  GroupCallGrid,
  GroupCallTile,
  IncomingCallBanner,
  IncomingCallScreen,
  callGridColumns,
  callGridLayout,
  callSpotlightIndex,
  resolveCallStatusLine,
} from './call-ui';
export type {
  CallControlButtonProps,
  CallControlKey,
  CallControlsProps,
  CallDirection,
  CallHistoryItem,
  CallHistoryListProps,
  CallHistoryRowProps,
  CallHistorySection,
  CallMinimisedPillProps,
  CallMode,
  CallPipCorner,
  CallScreenProps,
  CallStatus,
  GroupCallBarProps,
  GroupCallGridProps,
  GroupCallLayout,
  GroupCallParticipant,
  GroupCallTileProps,
  IncomingCallAnswerMode,
  IncomingCallBannerProps,
  IncomingCallScreenProps,
} from './call-ui';
export {
  ChannelPostCard,
  ContactList,
  ContactRow,
  MemberList,
  MemberRow,
  NewGroupForm,
  SelectedChipsRow,
  StoryProgressBars,
  StoryViewer,
  CONTACT_ALPHABET,
  contactSectionIndex,
  nameCounterTone,
  storyProgressFill,
  storyTapZone,
} from './chat-people';
export type {
  ChannelPostCardProps,
  ContactListProps,
  ContactRowProps,
  ContactSection,
  MemberListItem,
  MemberListProps,
  MemberRole,
  MemberRowProps,
  NewGroupFormProps,
  PersonSummary,
  SelectedChipsRowProps,
  StoryItem,
  StoryProgressBarsProps,
  StoryViewerProps,
} from './chat-people';
export {
  ChatBackground,
  chatBackgroundExtremes,
  chatBackgroundReferenceSurfaces,
  ChatDateHeader,
  ChatEmptyState,
  ChatHeader,
  ChatInfoPanel,
  ChatMemberRow,
  ChatSplitLayout,
  JumpToMentionButton,
  PinnedMessageBar,
  resolveChatScreenPaint,
  ScrollToBottomButton,
} from './chat-screen';
export type {
  ChatBackgroundProps,
  ChatBackgroundVariant,
  ChatDateHeaderPlacement,
  ChatDateHeaderProps,
  ChatEmptyStateProps,
  ChatHeaderMarker,
  ChatHeaderProps,
  ChatHeaderStatusTone,
  ChatInfoAction,
  ChatInfoPanelProps,
  ChatInfoPanelVariant,
  ChatInfoTab,
  ChatMember,
  ChatMemberRole,
  ChatMemberRowProps,
  ChatPane,
  ChatPinnedMessage,
  ChatScreenPaint,
  ChatSplitLayoutProps,
  JumpToMentionButtonProps,
  PinnedMessageBarProps,
  ScrollToBottomButtonProps,
} from './chat-screen';
export {
  AttachmentMenu,
  ATTACHMENT_MENU_ITEMS,
  ChatComposer,
  ComposerAttachmentStrip,
  ComposerBanner,
  ComposerIconButton,
  EmojiPicker,
  EMOJI_CATEGORY_ICONS,
  MessageContextMenu,
  ReactionPicker,
  REACTION_PICKER_EMOJIS,
  SKIN_TONE_MODIFIERS,
  SuggestionList,
  VoiceRecorder,
  applySkinTone,
  emojiChar,
  filterEmojiGroups,
  formatRecordingTime,
} from './chat-composer';
export type {
  AttachmentMenuItem,
  AttachmentMenuProps,
  ChatComposerAttachment,
  ChatComposerIcon,
  ChatComposerLabels,
  ChatComposerProps,
  ChatComposerSendOn,
  ChatComposerSuggestion,
  ComposerAttachmentStripProps,
  ComposerBannerKind,
  ComposerBannerProps,
  ComposerIconButtonProps,
  EmojiEntry,
  EmojiGroup,
  EmojiPickerLabels,
  EmojiPickerProps,
  EmojiPickerTab,
  MessageContextMenuProps,
  MessageMenuItem,
  ReactionPickerProps,
  SuggestionKind,
  SuggestionListProps,
  VoiceRecorderLabels,
  VoiceRecorderProps,
  VoiceRecorderState,
} from './chat-composer';
export {
  albumLayout,
  albumRows,
  ContactMessage,
  DocumentGrid,
  fileKindFor,
  fileTypeLabel,
  FileMessage,
  formatVoteCount,
  GifMessage,
  ImageMessage,
  LinkPreviewMessage,
  LocationMessage,
  MediaAlbum,
  nextPlaybackRate,
  pollPercentages,
  PollMessage,
  resampleWaveform,
  resolveBubbleColor,
  resolveMessageMediaPaint,
  seekPositionAt,
  SharedMediaGrid,
  StickerMessage,
  VideoMessage,
  VoiceMessage,
} from './message-media';
export type {
  AlbumCellRect,
  AlbumLayout,
  ContactMessageProps,
  DocumentGridItem,
  DocumentGridProps,
  FileKind,
  FileMessageProps,
  GifMessageProps,
  ImageMessageProps,
  LinkPreviewMessageProps,
  LocationMessageProps,
  MediaAlbumItem,
  MediaAlbumProps,
  MessageMediaPaint,
  MessageMediaSource,
  MessageMediaState,
  MessageMediaToneProps,
  MessageTone,
  PollMessageProps,
  PollOption,
  SharedMediaGridProps,
  SharedMediaItem,
  StickerMessageProps,
  VideoMessageProps,
  VideoMessageVariant,
  VoiceMessageProps,
  VoicePlaybackRate,
} from './message-media';
export {
  BUBBLE_RADIUS,
  BUBBLE_TAIL_RADIUS,
  CallSummaryRow,
  DateSeparator,
  MessageBubble,
  MessageGroup,
  MessageList,
  SystemMessage,
  TypingBubble,
  UnreadSeparator,
  bubblePositions,
  bubbleRadii,
  groupMessages,
  messageEntities,
  senderNameColor,
  splitMessageText,
} from './message-bubble';
export type {
  BubbleRadii,
  CallOutcome,
  CallSummaryRowProps,
  DateSeparatorProps,
  GroupedMessage,
  MessageBubbleLabels,
  MessageBubbleProps,
  MessageDirection,
  MessageEntity,
  MessageEntityType,
  MessageGroupProps,
  MessageListEntry,
  MessageListItem,
  MessageListProps,
  MessageMediaFit,
  MessagePosition,
  MessageReaction,
  MessageReplyPreview,
  MessageTextPart,
  SystemMessageProps,
  TypingBubbleProps,
  UnreadSeparatorProps,
} from './message-bubble';
export {
  ArchivedRow,
  CHAT_ATTACHMENT_ICONS,
  CHAT_ROW_GEOMETRY,
  CHAT_SEARCH_FIELD_HEIGHT,
  CHAT_SEARCH_KINDS,
  ChatFolderTabs,
  ChatList,
  ChatListItem,
  ChatListItemSkeleton,
  ChatSearchField,
  ChatSearchResults,
  GROUP_AVATAR_MAX_FACES,
  GroupAvatar,
  HighlightedText,
  NewChatButton,
  StoriesRow,
  groupSearchResults,
  hasUnread,
  highlightRuns,
  sortStories,
} from './chat-list';
export type {
  ArchivedRowProps,
  ChatAction,
  ChatActionTone,
  ChatAttachment,
  ChatAttachmentKind,
  ChatFace,
  ChatFolder,
  ChatFolderTabsProps,
  ChatKind,
  ChatListDensity,
  ChatListItemLabels,
  ChatListItemProps,
  ChatListItemSkeletonProps,
  ChatListLabels,
  ChatListProps,
  ChatListSection,
  ChatPreview,
  ChatRowGeometry,
  ChatSearchFieldProps,
  ChatSearchResult,
  ChatSearchResultKind,
  ChatSearchResultsLabels,
  ChatSearchResultsProps,
  ChatSummary,
  ChatSwipeActions,
  GroupAvatarProps,
  HighlightedRun,
  HighlightedTextProps,
  NewChatButtonProps,
  StoriesRowLabels,
  StoriesRowProps,
  StoryEntry,
} from './chat-list';
// The one drag affordance every list row in this library uses
export { SwipeRow, resolveSwipeRowPaint, swipeActionPaint, useSwipeAvailable } from './swipe-row';
export {
  SWIPE_ACTION_WIDTH,
  SWIPE_ACTIVATE_OFFSET,
  SWIPE_COMMIT_FRACTION,
  SWIPE_ROW_RADIUS,
  SWIPE_SNAP_DURATION,
  SWIPE_TAP_SLOP,
} from './swipe-row';
export type {
  SwipeRowAction,
  SwipeRowActionTone,
  SwipeRowActions,
  SwipeRowPaint,
  SwipeRowProps,
} from './swipe-row';
// Mail — the inbox, a thread, and writing a message
export {
  DEFAULT_MAIL_STRINGS,
  MAIL_LABEL_DOT,
  MAIL_ROW_GEOMETRY,
  MAIL_ROW_RADIUS,
  MAIL_SELECTION_BAR_HEIGHT,
  MailList,
  MailListSkeleton,
  MailRow,
  MailSelectionBar,
  composeMailRowName,
  groupMailByDay,
  labelMarks,
  mailStrings,
  resolveMailPaint,
  toSwipeActions,
  visibleLabels,
} from './mail-list';
export type {
  MailAction,
  MailActionPlacement,
  MailActionTone,
  MailDayGroupingOptions,
  MailDensity,
  MailLabel,
  MailListProps,
  MailListSection,
  MailListSkeletonProps,
  MailPaint,
  MailRowGeometry,
  MailRowNameInput,
  MailRowProps,
  MailSelectionBarProps,
  MailSender,
  MailStrings,
  MailSummary,
  MailSwipeActions,
} from './mail-list';
export {
  DEFAULT_MAIL_THREAD_STRINGS,
  MAIL_BODY_INSET,
  MAIL_THREAD_GEOMETRY,
  MailAddressLine,
  MailMessage,
  MailQuoteToggle,
  MailThread,
  addressName,
  collapseThread,
  defaultExpandedIds,
  mailThreadStrings,
  visibleAddresses,
} from './mail-thread';
export type {
  MailAddress,
  MailAddressLineProps,
  MailMessageProps,
  MailQuoteToggleProps,
  MailThreadAttachment,
  MailThreadEntry,
  MailThreadMessage,
  MailThreadProps,
  MailThreadStrings,
} from './mail-thread';
export {
  DEFAULT_MAIL_COMPOSE_STRINGS,
  MAIL_COMPOSE_GEOMETRY,
  MailComposeHeader,
  MailComposeSurface,
  MailRecipientField,
  copiesOpen,
  mailComposeStrings,
  recipientName,
  recipientsInvalid,
} from './mail-compose';
export type {
  MailComposeHeaderProps,
  MailComposeStrings,
  MailComposeSurfaceProps,
  MailComposeVariant,
  MailRecipient,
  MailRecipientFieldProps,
  MailRecipientSuggestion,
} from './mail-compose';
export {
  AlbumCard,
  ArtistCard,
  AudiobookCard,
  EpisodeCard,
  EventCard,
  FriendActivityCard,
  GenreCard,
  MediaCard,
  MixCard,
  PlaylistCard,
  PodcastCard,
  ProfileCard,
  QuickAccessTile,
  RecapCard,
  ShareCard,
  SongCard,
} from './media-card';
export type {
  AlbumCardProps,
  AlbumCardType,
  ArtistCardProps,
  AudiobookCardProps,
  EpisodeCardProps,
  EventCardProps,
  FriendActivityCardProps,
  GenreCardProps,
  MediaCardArtworkProps,
  MediaCardArtworkShape,
  MediaCardCommonProps,
  MediaCardLayout,
  MediaCardMenuItem,
  MediaCardPlayButton,
  MediaCardProps,
  MediaCardSize,
  MixCardProps,
  PlaylistCardProps,
  PodcastCardProps,
  ProfileCardProps,
  QuickAccessTileProps,
  RecapCardProps,
  RecapHighlight,
  ShareCardProps,
  SongCardArtist,
  SongCardProps,
} from './media-card';
export { FilterChips, Shelf, ShelfSkeleton, shelfGridColumns } from './media-shelf';
export type {
  FilterChipOption,
  FilterChipsProps,
  ShelfLayout,
  ShelfProps,
  ShelfSkeletonProps,
} from './media-shelf';
export {
  DEFAULT_QUEUE_PANEL_LABELS,
  moveQueueItem,
  QUEUE_ROW_HEIGHT,
  QueuePanel,
  QueuePanelRow,
  queueDragShift,
  queueDragTarget,
  RecentlyPlayedList,
} from './queue-panel';
export type {
  QueuePanelLabels,
  QueuePanelProps,
  QueuePanelRowProps,
  QueuePanelTab,
  QueuePanelVariant,
  QueueSection,
  QueueTrack,
  RecentlyPlayedListProps,
} from './queue-panel';
export {
  activeLyricIndex,
  LyricsPreviewCard,
  lyricsScrollTarget,
  LyricsView,
  normalizeLyricLines,
  resolveLyricsPalette,
} from './lyrics';
export type {
  LyricLine,
  LyricsPalette,
  LyricsPreviewCardProps,
  LyricsSize,
  LyricsViewProps,
} from './lyrics';
export {
  BrowseGrid,
  filterLibraryItems,
  LibraryItem,
  LibraryPanel,
  RecentSearches,
  SearchField,
  SearchResultTabs,
  sortLibraryItems,
  TopResultCard,
} from './music-library';
export type {
  BrowseGridProps,
  BrowseTile,
  LibraryEntry,
  LibraryFilter,
  LibraryFilterState,
  LibraryItemKind,
  LibraryItemProps,
  LibraryItemVariant,
  LibraryKindLabels,
  LibraryPanelLabels,
  LibraryPanelProps,
  LibrarySort,
  LibraryView,
  RecentSearchEntry,
  RecentSearchesProps,
  SearchFieldProps,
  SearchResultTab,
  SearchResultTabsProps,
  TopResultCardProps,
  TopResultKind,
} from './music-library';
export {
  ConnectBanner,
  DevicePicker,
  FullScreenPlayer,
  MiniPlayer,
  nextRepeatMode,
  NowPlayingBar,
  PLAYBACK_RATES,
  PlaybackSpeedMenu,
  resolveArtworkTint,
  SLEEP_TIMER_MINUTES,
  SleepTimerMenu,
  TransportControls,
} from './media-player';
export type {
  ConnectBannerProps,
  DevicePickerProps,
  FullScreenPlayerLabels,
  FullScreenPlayerProps,
  LyricsPreview,
  MediaArtist,
  MediaPlayerTrack,
  MiniPlayerProps,
  NowPlayingBarLabels,
  NowPlayingBarProps,
  PlaybackDevice,
  PlaybackDeviceKind,
  PlaybackSpeedMenuProps,
  RepeatMode,
  SleepTimerMenuProps,
  SleepTimerValue,
  TransportControlsLabels,
  TransportControlsProps,
  TransportControlsSize,
  TransportControlsVariant,
} from './media-player';
export {
  ArtistAbout,
  ArtistHero,
  ArtistPick,
  ArtistStats,
  AudiobookHeader,
  CollectionHeader,
  DEFAULT_DISCOGRAPHY_OPTIONS,
  DiscographyFilter,
  DownloadButton,
  EpisodeHeader,
  FollowButton,
  MediaActionBar,
  MediaIconButton,
  MediaMoreButton,
  PodcastShowHeader,
  PopularTracks,
  ProfileHeader,
  ShuffleButton,
  StickyMediaTopBar,
  TITLE_STEPS,
  mediaHeaderScrollProgress,
  resolveMediaHeaderPaint,
  selectTitleVariant,
  useMediaHeaderScroll,
} from './media-header';
export type {
  ArtistAboutProps,
  ArtistCity,
  ArtistHeroProps,
  ArtistPickProps,
  ArtistStat,
  ArtistStatsProps,
  AudiobookHeaderProps,
  CollectionHeaderProps,
  CollectionHeaderVariant,
  DiscographyFilterOption,
  DiscographyFilterProps,
  DownloadButtonProps,
  DownloadState,
  EpisodeHeaderProps,
  FollowButtonProps,
  LatestEpisode,
  MediaActionBarProps,
  MediaHeaderPaint,
  MediaHeaderPerson,
  MediaHeaderScrollOptions,
  MediaIconButtonProps,
  MediaImageSource,
  MediaMoreButtonProps,
  MediaViewMode,
  PodcastShowHeaderProps,
  PopularTrack,
  PopularTracksProps,
  ProfileHeaderProps,
  ProfileStat,
  ShuffleButtonProps,
  StickyMediaTopBarProps,
} from './media-header';
export {
  EpisodeList,
  EpisodeRow,
  SelectionBar,
  TrackList,
  TrackListEmpty,
  TrackListHeader,
  TrackRow,
  TrackRowSkeleton,
  resolveVisibleColumns,
} from './track-list';
export type {
  Episode,
  EpisodeListProps,
  EpisodeRowLabels,
  EpisodeRowProps,
  SelectionBarAction,
  SelectionBarPlacement,
  SelectionBarProps,
  Track,
  TrackArtist,
  TrackIconComponent,
  TrackListColumn,
  TrackListDensity,
  TrackListEmptyProps,
  TrackListGroup,
  TrackListHeaderProps,
  TrackListLabels,
  TrackListProps,
  TrackMenuItem,
  TrackRowNavigation,
  TrackRowPressEvent,
  TrackRowProps,
  TrackRowSkeletonProps,
} from './track-list';
export {
  AmenityFilter,
  AreaRangeFilter,
  AvailabilityFilter,
  CountFilter,
  ENERGY_RATINGS,
  EnergyRatingFilter,
  FLOOR_OPTIONS,
  FeatureFilter,
  FilterFooter,
  FilterSection,
  FilterTriggerButton,
  FloorFilter,
  HOUSING_FEATURE_OPTIONS,
  PROPERTY_TYPE_OPTIONS,
  PriceHistogram,
  PriceRangeFilter,
  PropertyTypeFilter,
  SegmentedFilter,
  SwitchFilterRow,
  ToggleChipGroup,
} from './stay-filters';
export type {
  AmenityFilterProps,
  AreaRangeFilterProps,
  AvailabilityFilterProps,
  CountFilterProps,
  EnergyRating,
  EnergyRatingFilterProps,
  FeatureFilterProps,
  FilterFooterProps,
  FilterIconComponent,
  FilterOption,
  FilterSectionProps,
  FilterTriggerButtonProps,
  FloorFilterProps,
  FloorOption,
  HousingFeature,
  PriceHistogramProps,
  PriceRangeFilterProps,
  PriceScale,
  PropertyType,
  PropertyTypeFilterProps,
  PropertyTypeOption,
  PropertyTypeTilesProps,
  SegmentedFilterProps,
  SwitchFilterRowProps,
  ToggleChipGroupProps,
  ToggleChipOption,
} from './stay-filters';

// Stays
export {
  DateFlexibilityChips,
  DestinationSuggestions,
  GuestPicker,
  StaySearchBar,
  StaySearchCompact,
  StaySearchPanel,
  StaySearchStep,
  applyGuestCount,
  minimumAdults,
} from './stay-search';
export type {
  DateFlexibilityChipsProps,
  DateFlexibilityOption,
  DestinationSuggestion,
  DestinationSuggestionsProps,
  GuestCounts,
  GuestKind,
  GuestPickerProps,
  StaySearchBarLabels,
  StaySearchBarProps,
  StaySearchCompactProps,
  StaySearchDates,
  StaySearchDatesMode,
  StaySearchPanelProps,
  StaySearchSegment,
  StaySearchStepProps,
} from './stay-search';
export {
  BudgetPicker,
  DEFAULT_BUDGET_PRESETS,
  DEFAULT_CONTRACT_LENGTHS,
  DEFAULT_HOME_SEARCH_MODE_LABELS,
  HOME_SEARCH_MODES,
  HOME_SEARCH_SEGMENTS,
  HomeSearchBar,
  MoveInPicker,
  PropertyTypePicker,
  SaveSearchButton,
  SavedSearchCard,
  SearchModeTabs,
  homeSearchSegments,
} from './home-search';
export type {
  BudgetPeriod,
  BudgetPickerProps,
  BudgetPreset,
  HomeSearchBarProps,
  HomeSearchMode,
  HomeSearchSegment,
  HomeSearchSegmentKeys,
  HomeSearchSegmentOverrides,
  MoveInOption,
  MoveInPickerLabels,
  MoveInPickerProps,
  MoveInTiming,
  MoveInValue,
  PropertyTypePickerProps,
  SavedSearchCardProps,
  SavedSearchIcon,
  SaveSearchButtonProps,
  SearchModeTabsProps,
} from './home-search';
export * from './listing-details';
export * from './property-insights';
export * from './tenancy';
export * from './eviction';
export * from './place-reviews';
export { BookingBar, BookingCard, PriceBreakdown, TRIP_STATUS, TripCard } from './booking';
export type {
  BookingBarProps,
  BookingCardProps,
  BookingFieldKey,
  BookingPriceProps,
  PriceBreakdownProps,
  PriceBreakdownRow,
  PriceBreakdownTone,
  TripCardOrientation,
  TripCardProps,
  TripStatus,
} from './booking';
export {
  APPLICATION_ITEM_STATUS,
  ActionBar,
  ApplicationChecklist,
  EXCHANGE_MODE_LABELS,
  ExchangeProposalCard,
  MORTGAGE_TERM_OPTIONS,
  MortgageCalculator,
  RENTAL_STATUS,
  RentalActionCard,
  SALE_STATUS,
  SaleActionCard,
  ViewingScheduler,
  computeMortgage,
} from './listing-actions';
export type {
  ActionBarProps,
  ApplicationChecklistProps,
  ApplicationItem,
  ApplicationItemStatus,
  ExchangeHome,
  ExchangeLayout,
  ExchangeMode,
  ExchangeProposalCardProps,
  KeyFact,
  MortgageCalculatorLabels,
  MortgageCalculatorProps,
  MortgageInput,
  MortgageResult,
  RentalActionCardProps,
  RentalStatus,
  SaleActionCardProps,
  SaleStatus,
  ViewingDay,
  ViewingMode,
  ViewingSchedulerProps,
  ViewingSlot,
} from './listing-actions';
export { FavoriteButton, ListingCard, ListingCardGrid, WishlistCard } from './listing-card';
export type {
  FavoriteButtonProps,
  ListingCardDensity,
  ListingCardGridProps,
  ListingCardLayout,
  ListingCardProps,
  ListingFact,
  ListingFactIcon,
  ListingPriceLine,
  ListingStatus,
  Offering,
  WishlistCardProps,
} from './listing-card';
export { OfferingBadge } from './offering-badge';
export type {
  OfferingBadgeIcon,
  OfferingBadgeProps,
  OfferingBadgeSize,
  OfferingBadgeVariant,
} from './offering-badge';
export { CategoryBar } from './category-bar';
export type { CategoryBarIcon, CategoryBarItem, CategoryBarProps } from './category-bar';
export {
  MapAreaCircle,
  MapClusterMarker,
  MapListingPreview,
  MapPriceMarker,
  MapSearchAreaButton,
} from './map-marker';

// Maps — the chrome an app draws OVER a map it supplies. No engine, no tiles:
// a place, the way there, and the controls that float on top.
export { PlaceActions, PlaceCard } from './place-card';
export { PLACE_CARD_GEOMETRY, PLACE_OPEN_LABELS, PLACE_OPEN_TONE } from './place-card';
export { composePlaceName, openLabelFor, resolvePlaceCardPaint } from './place-card';
export type {
  PlaceAction,
  PlaceActionsProps,
  PlaceCardDensity,
  PlaceCardGeometry,
  PlaceCardPaint,
  PlaceCardProps,
  PlaceOpenState,
  PlaceStat,
} from './place-card';
export {
  PlaceAmenities,
  PlaceHours,
  PlaceInfoList,
  PlacePopularTimes,
  PlaceTransit,
} from './place-details';
export {
  PLACE_BUSY_LABELS,
  PLACE_DETAILS_GEOMETRY,
  PLACE_INFO_ACTION_LABELS,
  PLACE_INFO_ACTION_ICON,
  PLACE_TRANSIT_MODE_ICON,
  PLACE_TRANSIT_MODE_LABELS,
} from './place-details';
export {
  busyTrendLabel,
  describeBusyChart,
  describeDeparture,
  describeHoursDay,
  describeInfoItem,
  describeTransitStop,
  formatHoursDay,
  infoActionWord,
  resolvePlaceDetailsPaint,
} from './place-details';
export type {
  HoursFormat,
  PlaceAmenitiesLayout,
  PlaceAmenitiesProps,
  PlaceAmenity,
  PlaceBusyHour,
  PlaceBusyTrend,
  PlaceDetailsGeometry,
  PlaceDetailsPaint,
  PlaceHoursDay,
  PlaceHoursInterval,
  PlaceHoursProps,
  PlaceInfoAction,
  PlaceInfoItem,
  PlaceInfoListProps,
  PlacePopularTimesDay,
  PlacePopularTimesProps,
  PlaceTransitDeparture,
  PlaceTransitMode,
  PlaceTransitProps,
  PlaceTransitStop,
} from './place-details';
export { PlaceList, PlaceListCard } from './place-list';
export {
  DEFAULT_PLACE_LIST_LABELS,
  PLACE_LIST_GEOMETRY,
  PLACE_LIST_VISIBILITY_ICON,
  PLACE_LIST_VISIBILITY_LABELS,
  composePlaceListName,
  placeListCountLabel,
  placeListSharedWithLabel,
  resolvePlaceListPaint,
} from './place-list';
export type {
  PlaceListCardProps,
  PlaceListGeometry,
  PlaceListLabels,
  PlaceListPaint,
  PlaceListPlace,
  PlaceListProps,
  PlaceListVisibility,
} from './place-list';
export { MapCompass, MapControls, MapLayerPicker } from './map-controls';
export { MAP_CONTROL_BOX, MAP_CONTROLS_GEOMETRY } from './map-controls';
export type {
  MapCompassProps,
  MapControlsAlign,
  MapControlsGeometry,
  MapControlsLabels,
  MapControlsProps,
  MapLayerOption,
  MapLayerPickerLabels,
  MapLayerPickerProps,
  MapOverlayOption,
} from './map-controls';

// Drawn ON the map rather than around it: where you are, the guidance while it
// is happening, and the small print the data's licence requires. Built on the
// two families above — the accuracy halo IS `map-marker`'s area circle, the
// maneuver glyphs ARE `directions`' own, and the guidance rides on the same
// glass island the map controls do.
export { LocationPuck } from './location-puck';
export {
  LOCATION_PUCK_CONE_STOPS,
  LOCATION_PUCK_GEOMETRY,
  LOCATION_PUCK_PULSE_MS,
  LOCATION_PUCK_STALE_OPACITY,
  LOCATION_PUCK_STATE_LABELS,
} from './location-puck';
export { coneHalfAngle, describeLocationPuck, resolveLocationPuckPaint } from './location-puck';
export type {
  LocationPuckGeometry,
  LocationPuckMode,
  LocationPuckPaint,
  LocationPuckProps,
  LocationPuckState,
} from './location-puck';
export { ArrivalBar, LaneGuidance, NavigationBanner, SpeedLimitPill } from './navigation-banner';
export {
  NAVIGATION_BANNER_GEOMETRY,
  NAVIGATION_STATE_ICON,
  NAVIGATION_STATE_LABELS,
  NAVIGATION_STATE_TONE,
} from './navigation-banner';
export {
  describeArrival,
  describeLanes,
  describeNavigationBanner,
  describeSpeedLimit,
  maneuverWordFor,
  resolveNavigationPaint,
} from './navigation-banner';
export type {
  ArrivalBarLabels,
  ArrivalBarProps,
  LaneDirection,
  LaneGuidanceLabels,
  LaneGuidanceProps,
  NavigationBannerGeometry,
  NavigationBannerLabels,
  NavigationBannerProps,
  NavigationBannerState,
  NavigationLane,
  NavigationPaint,
  SpeedLimitPillProps,
} from './navigation-banner';
export { MapAttribution, MapScaleBar } from './map-attribution';
export { MAP_ATTRIBUTION_GEOMETRY } from './map-attribution';
export { describeScale, resolveMapAttributionPaint } from './map-attribution';
export type {
  MapAttributionGeometry,
  MapAttributionPaint,
  MapAttributionProps,
  MapAttributionVariant,
  MapScale,
  MapScaleBarProps,
} from './map-attribution';

// Commerce — what any app that moves a thing from A to B needs: where the
// thing is, what it costs, where it is going, and the stops on the way. Shared
// on purpose: a parcel, a food order and a booking are the same four questions.
export { OrderStatusBar, OrderStatusTimeline } from './order-status';
export { ORDER_STATUS_GEOMETRY, ORDER_STATUS_STATE_LABELS, resolveOrderStatusPaint } from './order-status';
export type {
  OrderStatusBarProps,
  OrderStatusBarVariant,
  OrderStatusDensity,
  OrderStatusGeometry,
  OrderStatusOrientation,
  OrderStatusPaint,
  OrderStatusProgress,
  OrderStatusStep,
  OrderStatusStepState,
  OrderStatusTimelineProps,
} from './order-status';
export { PriceSummary, PriceSummaryLine } from './price-breakdown';
export { PRICE_PENDING_PLACEHOLDER, PRICE_STATE_LABELS, resolvePricePaint } from './price-breakdown';
export type {
  PriceLine,
  PriceLineState,
  PriceLineTone,
  PricePaint,
  PriceStateLabels,
  PriceSummaryLineProps,
  PriceSummaryProps,
  PriceTotal,
} from './price-breakdown';

// Ordering food: who is cooking, what they cook, and what is in the basket.
// Three families on top of the commerce four above — the vendor card is
// `listing-card`'s card with a vendor's data in it, the basket's totals are
// `PriceSummary`, and order tracking is `order-status`.
export { VendorCard } from './vendor-card';
export {
  VENDOR_AVAILABILITY_LABELS,
  VENDOR_FACT_ICON,
  VENDOR_FACT_LABELS,
  VENDOR_FACT_ORDER,
  VENDOR_PHOTO_ASPECT_RATIO,
  availabilityLabelFor,
  composeVendorName,
  vendorCuisines,
  vendorFacts,
} from './vendor-card';
export type {
  VendorAvailability,
  VendorCardDensity,
  VendorCardProps,
  VendorFactKey,
} from './vendor-card';
export { MenuItemOptions, MenuItemRow } from './menu-item';
export {
  MENU_ITEM_DIETS,
  MENU_ITEM_DIET_LABELS,
  MENU_ITEM_GEOMETRY,
  MENU_ITEM_SPICE_MAX,
  composeMenuItemName,
  describeOptionRule,
  describeSpice,
  optionDisabled,
  optionGroupRule,
  optionSubtitle,
  resolveMenuItemPaint,
  spiceLevel,
  toggleOptionSelection,
} from './menu-item';
export type {
  MenuItemDensity,
  MenuItemDiet,
  MenuItemGeometry,
  MenuItemOption,
  MenuItemOptionGroup,
  MenuItemOptionRule,
  MenuItemOptionsProps,
  MenuItemPaint,
  MenuItemRowProps,
} from './menu-item';
export { CartLine, CartPanel, CartPromoField, CartTipPicker } from './cart-panel';
export {
  CART_BLOCK_GAP,
  CART_GEOMETRY,
  CART_LINE_GAP,
  CART_WASH_OPACITY,
  composeCartLineName,
  optionsLine,
  resolveCartPaint,
} from './cart-panel';
export type {
  CartDensity,
  CartGeometry,
  CartLineEntry,
  CartLineProps,
  CartMinimumOrder,
  CartPaint,
  CartPanelProps,
  CartPromoFieldProps,
  CartSummary,
  CartTipOption,
  CartTipPickerProps,
} from './cart-panel';
export { AddressList, AddressRow } from './address';
export { ADDRESS_GEOMETRY, ADDRESS_KIND_ICON, resolveAddressPaint } from './address';
export type {
  AddressDensity,
  AddressGeometry,
  AddressKind,
  AddressListEntry,
  AddressListProps,
  AddressListSection,
  AddressListVariant,
  AddressPaint,
  AddressRowProps,
} from './address';
export { RouteStops } from './route-stops';
export { ROUTE_STOPS_GEOMETRY, ROUTE_STOP_STATE_LABELS } from './route-stops';
export type {
  RouteStop,
  RouteStopState,
  RouteStopsGeometry,
  RouteStopsLabels,
  RouteStopsProps,
} from './route-stops';
export { DirectionsSteps, DirectionsSummary, TransitLineBadge } from './directions';
export {
  DIRECTIONS_LEG_GLYPH,
  DIRECTIONS_MANEUVER_ICON,
  DIRECTIONS_MANEUVER_LABELS,
  DIRECTIONS_MODE_ICON,
  DIRECTIONS_MODE_LABELS,
  DIRECTIONS_TRAFFIC_LABELS,
  DIRECTIONS_TRAFFIC_TONE,
} from './directions';
export {
  describeRoute,
  describeStep,
  describeTransitLine,
  modeLabelFor,
  resolveDirectionsPaint,
  resolveTransitLineColors,
  trafficLabelFor,
} from './directions';
export type {
  DirectionsLeg,
  DirectionsManeuver,
  DirectionsMode,
  DirectionsPaint,
  DirectionsRoute,
  DirectionsStep,
  DirectionsStepsProps,
  DirectionsSummaryLabels,
  DirectionsSummaryProps,
  DirectionsTraffic,
  TransitLine,
  TransitLineBadgeProps,
  TransitLineColors,
} from './directions';

// Checkout — the distance between "I want this" and "it is ordered": the
// review a buyer confirms, the window they pick, and the screen that says it
// happened. Built on the commerce block above — the totals ARE `PriceSummary`,
// the address row IS `AddressRow`, and the tracking strip IS `OrderStatusBar`.
export { CheckoutConfirm, CheckoutSummary, CheckoutSummaryRow } from './checkout-summary';
export {
  CHECKOUT_AMOUNT_SEPARATOR,
  CHECKOUT_CONFIRM_BUSY_LABEL,
  CHECKOUT_CONFIRM_LABEL,
  CHECKOUT_GROUP_RADIUS,
  CHECKOUT_ROW_HINT,
  CHECKOUT_ROW_ICON,
  CHECKOUT_ROW_PLACEHOLDER,
  CHECKOUT_ROW_TILE,
  checkoutConfirmLabel,
  checkoutRowName,
  resolveCheckoutPaint,
} from './checkout-summary';
export type {
  CheckoutAddressSummary,
  CheckoutConfirmProps,
  CheckoutSummaryLine,
  CheckoutSummaryPaint,
  CheckoutSummaryProps,
  CheckoutSummaryRowProps,
} from './checkout-summary';
export { DeliverySlotDays, DeliverySlotOption, DeliverySlotPicker } from './delivery-slot';
export {
  DELIVERY_ASAP_LABEL,
  DELIVERY_DAY_LABEL,
  DELIVERY_EMPTY_DESCRIPTION,
  DELIVERY_EMPTY_TITLE,
  DELIVERY_FIELD_LABEL,
  DELIVERY_OPTION_RADIUS,
  DELIVERY_SOLD_OUT_LABEL,
  DELIVERY_TIER_LABELS,
  joinDeliveryParts,
  resolveDeliverySlotPaint,
  windowDetail,
  windowName,
} from './delivery-slot';
export type {
  DeliveryAsapOption,
  DeliveryDay,
  DeliverySlotDaysProps,
  DeliverySlotOptionProps,
  DeliverySlotPaint,
  DeliverySlotPickerProps,
  DeliveryTier,
  DeliveryWindow,
} from './delivery-slot';
export { OrderConfirmation } from './order-confirmation';
export {
  ORDER_CONFIRMATION_ITEMS_LABEL,
  ORDER_CONFIRMATION_MARK,
  ORDER_CONFIRMATION_REFERENCE_LABEL,
  ORDER_CONFIRMATION_TITLE,
} from './order-confirmation';
export type {
  OrderConfirmationAddress,
  OrderConfirmationFact,
  OrderConfirmationProps,
} from './order-confirmation';

// Freight — asking a marketplace to carry something: describing the load and
// the route, the offers that come back, and the vehicle the job needs. Built
// on the commerce block above: the route IS `route-stops`, the itemisation IS
// `price-breakdown`, and the tracking IS `order-status`.
export { ShipmentLoadPicker, ShipmentOptionsList, ShipmentRequestForm } from './shipment-request';
export {
  SHIPMENT_ACCESS_OPTIONS,
  SHIPMENT_LOAD_KINDS,
  SHIPMENT_LOAD_LABELS,
  SHIPMENT_LOAD_SIZES,
  SHIPMENT_OPTIONS_LABELS,
  SHIPMENT_REQUEST_GEOMETRY,
  SHIPMENT_REQUEST_LABELS,
  isShipmentLoadComplete,
  joinShipmentName,
  sanitizeWeight,
  toggleShipmentExtra,
} from './shipment-request';
export type {
  ShipmentAccess,
  ShipmentAccessOption,
  ShipmentExtra,
  ShipmentLoad,
  ShipmentLoadErrors,
  ShipmentLoadKind,
  ShipmentLoadKindOption,
  ShipmentLoadPickerLabels,
  ShipmentLoadPickerProps,
  ShipmentLoadSize,
  ShipmentLoadSizeOption,
  ShipmentOptionsLabels,
  ShipmentOptionsListProps,
  ShipmentRequestFormLabels,
  ShipmentRequestFormProps,
  ShipmentRequestGeometry,
  ShipmentTimeWindow,
} from './shipment-request';
export { CarrierQuoteCard, CarrierQuoteList } from './carrier-quote';
export {
  CARRIER_QUOTE_GEOMETRY,
  CARRIER_QUOTE_LABELS,
  CARRIER_QUOTE_MARK_ORDER,
  CARRIER_QUOTE_MARK_TONE,
  CARRIER_QUOTE_SORTS,
  carrierActionsAreLabelled,
  markCarrierQuotes,
  orderCarrierMarks,
  resolveCarrierQuotePaint,
  sortCarrierQuotes,
} from './carrier-quote';
export type {
  CarrierQuote,
  CarrierQuoteCardProps,
  CarrierQuoteCarrier,
  CarrierQuoteDensity,
  CarrierQuoteGeometry,
  CarrierQuoteLabels,
  CarrierQuoteListProps,
  CarrierQuoteMark,
  CarrierQuotePaint,
  CarrierQuoteSort,
} from './carrier-quote';
export { VehiclePicker } from './vehicle-picker';
export {
  VEHICLE_ICON,
  VEHICLE_OPTIONS,
  VEHICLE_PICKER_GEOMETRY,
  VEHICLE_PICKER_LABELS,
  vehicleOptionName,
} from './vehicle-picker';
export type {
  VehicleKind,
  VehicleOption,
  VehiclePickerGeometry,
  VehiclePickerLabels,
  VehiclePickerProps,
} from './vehicle-picker';

// TAKING THE MONEY. `payment-method` is the saved way to pay, `card-form` is
// entering a new one, and `payment-status` is what happened afterwards. None of
// the three holds card data: the masked string, the value and the processor's
// verdict all belong to the app.
export { PaymentMethodList, PaymentMethodMark, PaymentMethodRow } from './payment-method';
export {
  PAYMENT_METHOD_GEOMETRY,
  PAYMENT_METHOD_KIND_ICON,
  PAYMENT_METHOD_LIST_GAP,
  PAYMENT_METHOD_MARK_GAP,
  PAYMENT_METHOD_STATE_LABELS,
  PAYMENT_METHOD_STATE_TONE,
  composePaymentMethodName,
  paymentMethodStateMessage,
  resolvePaymentMethodPaint,
} from './payment-method';
export type {
  PaymentMethodDensity,
  PaymentMethodEntry,
  PaymentMethodGeometry,
  PaymentMethodKind,
  PaymentMethodListProps,
  PaymentMethodListVariant,
  PaymentMethodMarkProps,
  PaymentMethodPaint,
  PaymentMethodRowProps,
  PaymentMethodState,
} from './payment-method';
export {
  CardForm,
  CardFormCountry,
  CardFormExpiry,
  CardFormName,
  CardFormNumber,
  CardFormPostcode,
  CardFormSecurityCode,
} from './card-form';
export {
  CARD_FORM_EMPTY_VALUE,
  CARD_FORM_GAP,
  CARD_FORM_LABELS,
  CARD_FORM_PLACEHOLDERS,
  DEFAULT_CARD_GROUPS,
  DEFAULT_CARD_LENGTHS,
  DEFAULT_SECURITY_CODE_LENGTH,
  applyCardExpiryEdit,
  applyCardNumberEdit,
  cardDigits,
  cardExpiryIsWellFormed,
  cardNumberIsWellFormed,
  cardSecurityCodeIsWellFormed,
  groupCardDigits,
  luhnCheck,
  matchCardScheme,
  normaliseCardExpiry,
  normaliseCardNumber,
  schemeGroups,
  schemeLengths,
  schemeMaxDigits,
  schemeSecurityCodeLength,
  useCardFormPart,
} from './card-form';
export type {
  CardFormCountryOption,
  CardFormCountryProps,
  CardFormErrors,
  CardFormExpiryProps,
  CardFormFieldName,
  CardFormFields,
  CardFormLabels,
  CardFormNameProps,
  CardFormNumberProps,
  CardFormPartInput,
  CardFormPartMembership,
  CardFormPostcodeProps,
  CardFormProps,
  CardFormSecurityCodeProps,
  CardFormValue,
  CardScheme,
} from './card-form';
export { PaymentStatusBar, PaymentStatusBlock } from './payment-status';
export {
  PAYMENT_STATUS_ADMONITION,
  PAYMENT_STATUS_GEOMETRY,
  PAYMENT_STATUS_ICON,
  PAYMENT_STATUS_LABELS,
  PAYMENT_STATUS_TONE,
  resolvePaymentStatus,
  resolvePaymentStatusPaint,
} from './payment-status';
export type {
  PaymentStatusBarProps,
  PaymentStatusBlockProps,
  PaymentStatusGeometry,
  PaymentStatusLabels,
  PaymentStatusPaint,
  PaymentStatusPresentation,
  PaymentStatusState,
} from './payment-status';

export { WizardFooter, WizardProgress } from './wizard';
export type { WizardFooterProps, WizardProgressProps, WizardStep } from './wizard';
export { SortablePhotoGrid } from './sortable-media';
export type {
  SortablePhoto,
  SortablePhotoGridLabels,
  SortablePhotoGridProps,
  SortablePhotoStatus,
} from './sortable-media';
export {
  AddressPrecisionPicker,
  DEFAULT_ADDRESS_PRECISION_OPTIONS,
  DEFAULT_PROPERTY_TYPES,
  ListingPreviewPane,
  ListingQualityMeter,
  listingQualityScore,
  OfferingEditor,
  PrecisionMapPlaceholder,
  PropertyTypeSelector,
} from './listing-editor';
export type {
  AddressPrecision,
  AddressPrecisionOption,
  AddressPrecisionPickerProps,
  ListingEditorIcon,
  ListingPreviewData,
  ListingPreviewMode,
  ListingPreviewPaneProps,
  ListingQualityItem,
  ListingQualityMeterProps,
  OfferingCardCopy,
  OfferingEditorLabels,
  OfferingEditorProps,
  OfferingErrors,
  OfferingField,
  OfferingKind,
  OfferingValue,
  PropertyTypeSelectorProps,
  RentOffering,
  SaleOffering,
  StayOffering,
  SwapMode,
  SwapOffering,
} from './listing-editor';
export type {
  MapAreaCircleProps,
  MapClusterMarkerProps,
  MapListingPreviewLayout,
  MapListingPreviewProps,
  MapMarkerState,
  MapPriceMarkerProps,
  MapPriceMarkerSize,
  MapSearchAreaButtonProps,
} from './map-marker';
export * from './chip';
export * from './aspect-ratio';
export * from './tabs';
export * from './checkbox';
export * from './radio';
export * from './accordion';
export { LinkPreviewCard } from './link-preview';
export type { LinkPreviewCardProps } from './link-preview';

// Stat / profile widgets
export { CompositionBar } from './composition-bar';
export type { CompositionBarProps, CompositionCategory } from './composition-bar';
export { DotGridMeter } from './dot-grid-meter';
export type { DotGridMeterProps } from './dot-grid-meter';
export { Meter, MeterRing, StatBar, meterFraction, meterValue, resolveMeterColors } from './stat-bar';
export type {
  AnyMeterProps,
  MeterColors,
  MeterDecorativeProps,
  MeterProps,
  MeterRingProps,
  StatBarProps,
  StatBarProgressProps,
  StatBarSplitProps,
  StatBarVariant,
} from './stat-bar';
export { ActivityHeatmap, bucketByDay } from './activity-heatmap';
export type { ActivityHeatmapProps, ActivityHeatmapDay } from './activity-heatmap';

// Settings / Grouped list
export * from './settings-list';
export { Item } from './item';
export type { ItemProps } from './item';
export { Kbd } from './kbd';
export type { KbdProps } from './kbd';

// Overlay components
export * from './admonition';
export * from './dropdown-menu/index.web';
export * from './tooltip/index.web';
export * from './select/index.web';
export * from './context-menu/index.web';
export * from './menubar/index.web';
export * from './popover/index.web';
export * from './hover-card/index.web';
export { AlertDialog } from './alert-dialog/index.web';
export type { AlertDialogProps, AlertDialogActionStyle } from './alert-dialog/index.web';
export { Command } from './command/index.web';
export type { CommandProps, CommandItem } from './command/index.web';

// Code (mono)
export * as Code from './code';

// Fonts
export * as Fonts from './fonts/index.web';
export * from './creator-studio';

// CRM — people and companies, deals and the board they move on, what was done
// with a customer, and how good a lead is. Named exports rather than `export *`
// so the barrel says what each family publishes: `chat-people` already offers a
// `ContactRow` and `chart-cards` an `ActivityDay`, and a star export is how two
// families come to disagree about one name without anything failing.
export {
  ContactProfileCard,
  CONTACT_AVATAR_OVERLAP,
  CONTACT_AVATAR_SIZE,
  CONTACT_CHANNEL,
  CONTACT_CHANNEL_HIT,
  CONTACT_CHANNEL_SIZE,
  CONTACT_CONTENT_TOP,
  CONTACT_COVER_HEIGHT,
  CONTACT_NARROW_WIDTH,
  CONTACT_OWNER_AVATAR_SIZE,
  CONTACT_PROFILE_PADDING,
  CONTACT_ROW_MIN_HEIGHT,
  CONTACT_TILE_PADDING,
  CONTACT_TILE_RADIUS,
  contactActionsAreLabelled,
  contactCoverWash,
  contactMetaLine,
  contactStatRows,
  resolveContactPaint,
} from './contact-card';
export type {
  ContactChannel,
  ContactChannelKind,
  ContactOwner,
  ContactPaint,
  ContactProfileCardProps,
  ContactProfileDensity,
  ContactProfileHeadline,
  ContactProfilePerson,
  ContactProfileStat,
  ContactStatus,
  ContactSubjectKind,
} from './contact-card';
export {
  DealCard,
  DEAL_CARD_PADDING,
  DEAL_HEALTH,
  PipelineBoard,
  PipelineColumn,
  PIPELINE_CARD_GAP,
  PIPELINE_COLUMN_PADDING,
  PIPELINE_COLUMN_WIDTH,
  PIPELINE_SINGLE_MAX_WIDTH,
  PIPELINE_SKELETON_CARDS,
  dealHealthLabel,
  dealHealthTone,
  pipelineColumnFill,
  resolvePipelinePaint,
} from './pipeline';
export type {
  DealCardProps,
  DealHealth,
  DealOwner,
  PipelineBoardLayout,
  PipelineBoardProps,
  PipelineColumnProps,
  PipelinePaint,
  PipelineStage,
} from './pipeline';
export {
  ActivityFeed,
  ActivityFeedFilters,
  ACTIVITY_AVATAR_SIZE,
  ACTIVITY_BODY_CHARS_PER_LINE,
  ACTIVITY_ENTRY_GAP,
  ACTIVITY_FEED_KIND,
  ACTIVITY_FEED_KINDS,
  ACTIVITY_KIND_MARK_SIZE,
  activityBodyIsLong,
  groupActivityByDay,
  resolveActivityFeedPaint,
} from './activity-feed';
export type {
  ActivityFeedActor,
  ActivityFeedEntry,
  ActivityFeedFiltersProps,
  ActivityFeedGroup,
  ActivityFeedKind,
  ActivityFeedPaint,
  ActivityFeedProps,
} from './activity-feed';
export {
  LeadScoreCard,
  LEAD_FACTOR_MARK_RADIUS,
  LEAD_FACTOR_MARK_SIZE,
  LEAD_FACTOR_ROW_PADDING,
  LEAD_SCORE_BAND,
  LEAD_SCORE_CARD_PADDING,
  LEAD_SCORE_PANEL_GAP,
  LEAD_SCORE_PANEL_PADDING,
  LEAD_SCORE_PANEL_RADIUS,
  LEAD_SCORE_RING_SIZE,
  LEAD_SCORE_RING_THICKNESS,
  LEAD_SCORE_THRESHOLDS,
  LEAD_SCORE_TREND,
  factorLine,
  formatContribution,
  resolveLeadScoreBand,
  resolveLeadScorePaint,
} from './lead-score';
export type {
  LeadScoreBand,
  LeadScoreCardProps,
  LeadScoreFactor,
  LeadScorePaint,
  LeadScoreTrend,
} from './lead-score';
// Notes and long documents
export * from './note-card';
export * from './note-editor';
export * from './outline-nav';
export * from './tag-field';
