// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/avatar-group/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { AvatarGroup } from './AvatarGroup.web';
export type { AvatarGroupProps, AvatarGroupItem } from './types';
