// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/project-board/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ProjectBoard } from './ProjectBoard.web';
export type {
  BoardSort,
  NewProjectTicket,
  ProjectBoardProps,
  ProjectColumn,
  ProjectMember,
  ProjectTicket,
  TicketComment,
  TicketPriority,
  TicketSubtask,
} from './types';
