import type { AgentLanguage, AgentPreferences } from './types';
export const AGENT_LANGUAGES = [
  { id: 'auto', label: 'Auto-detect' },
  { id: 'en', label: 'English' },
  { id: 'tr', label: 'Turkish' },
  { id: 'es', label: 'Spanish' },
  { id: 'fr', label: 'French' },
  { id: 'de', label: 'German' },
  { id: 'ja', label: 'Japanese' },
  { id: 'pt', label: 'Portuguese' },
] as const;
export const AGENT_SPEECH_RATES = [0.75, 1, 1.25, 1.5] as const;
export const DEFAULT_AGENT_PREFERENCES: AgentPreferences = {
  voice: 'alice',
  speed: 1,
  language: 'auto',
  notifications: true,
};
export const AVATAR_COLORS = [
  [220, 85, 'Blue', '#437EF7', '#004DE9'],
  [181, 49, 'Teal', '#27b5a2', '#00957c'],
  [259, 75, 'Violet', '#8554F6', '#3E00CD'],
  [321, 74, 'Pink', '#E34798', '#D3006D'],
  [0, 78, 'Red', '#E74241', '#CF0100'],
  [31, 89, 'Orange', '#f47327', '#d83f00'],
  [193, 78, 'Cyan', '#1bb4ce', '#0093ad'],
  [78, 72, 'Lime', '#88c81c', '#6aa400'],
  [145, 51, 'Green', '#36c15c', '#009f13'],
] as const;
export const EMOTION_NAMES = {
  neutral: 'Neutral',
  happy: 'Happy',
  angry: 'Angry',
  thinking: 'Thinking',
  shook: 'Shook',
  curious: 'Curious',
  wink: 'Wink',
  sleepy: 'Sleepy',
  sad: 'Sad',
  worried: 'Worried',
  skeptical: 'Skeptical',
  focused: 'Focused',
  excited: 'Excited',
  calm: 'Calm',
  shy: 'Shy',
  confused: 'Confused',
} as const;
export const PREVIEW_TEXT: Record<AgentLanguage, string> = {
  auto: 'Hello! Ready when you are.',
  en: 'Hello! Ready when you are.',
  tr: 'Merhaba! Hazır olduğunda başlayabiliriz.',
  es: '¡Hola! Podemos empezar cuando quieras.',
  fr: 'Bonjour ! Nous pouvons commencer quand vous voulez.',
  de: 'Hallo! Wir können anfangen, wenn du bereit bist.',
  ja: 'こんにちは！準備ができたら始めましょう。',
  pt: 'Olá! Podemos começar quando quiser.',
};

// Recovered engine catalog metadata. IDs are renderer selections; titles retain the beta catalog's English defaults.
export const CHARACTER_PRESETS = [
  { id: 'clippo', title: 'Clippo' },
  { id: 'blue_beret', title: 'Felipe' },
  { id: 'alfred', title: 'Alfred' },
  { id: 'purple_heart', title: 'Jojo' },
  { id: 'lime_frog', title: 'Todd' },
  { id: 'coral_monocle', title: 'Iris' },
  { id: 'gus', title: 'Thelma' },
  { id: 'blue_spectacles', title: 'Josh' },
  { id: 'lime_headphones', title: 'Iggy' },
] as const;
export const CHARACTER_OPTIONS = {
  shape: [
    ['clippo', 'Clippo'],
    ['circle', 'Circle'],
    ['rounded_triangle', 'Rounded triangle'],
    ['capsule', 'Capsule'],
    ['rounded_head_two_ears', 'Rounded head with two ears'],
    ['six_lobed_flower', 'Six lobed flower'],
    ['heart', 'Heart'],
    ['four_lobed_butterfly', 'Four lobed butterfly'],
    ['circle_two_ears', 'Circle with two ears'],
    ['twelve_scalloped_rosette', 'Twelve scalloped rosette'],
    ['rounded_cube', 'Hexagon'],
    ['rounded_diamond', 'Rounded diamond'],
  ],
  color: [
    ['pink', 'Pink'],
    ['orchid', 'Orchid'],
    ['violet', 'Violet'],
    ['blue', 'Blue'],
    ['cyan', 'Cyan'],
    ['teal', 'Teal'],
    ['lime', 'Lime'],
    ['yellow', 'Yellow'],
    ['coral', 'Coral'],
  ],
  eyes: [
    ['clippo', 'Clippo'],
    ['todd', 'Todd'],
    ['swept_lids', 'Swept lids'],
    ['oval', 'Oval'],
    ['sparkle_capsules', 'Sparkle capsules'],
    ['highlight_capsules', 'Highlight capsules'],
    ['dots', 'Dots'],
    ['double_highlights', 'Round highlights'],
    ['round_inset', 'Round inset'],
    ['crescent_inset', 'Crescent inset'],
    ['sleepy_lids', 'Sleepy lids'],
  ],
  eyewear: [
    ['none', 'None'],
    ['monocle', 'Monocle'],
    ['tall_oval_frames', 'Tall oval frames'],
    ['separate_trapezoid_lenses', 'Separate trapezoid lenses'],
    ['classic_sunglasses', 'Classic sunglasses'],
    ['round_sunglasses', 'Round sunglasses'],
  ],
  accessory: [
    ['headphones', 'Headphones'],
    ['bow', 'Bow tie'],
    ['beanie', 'Beanie'],
    ['hat', 'Hat'],
    ['beret', 'Beret'],
    ['felipe_beret', 'Felipe’s beret'],
    ['orb', 'Bulb'],
    ['three_lobe', 'Tuft'],
    ['crown', 'Crown'],
  ],
} as const;

/** RGB swatches returned by the recovered engine's Color catalog. */
export const CHARACTER_COLORS = {
  pink: '#fa70ab',
  orchid: '#dd6adc',
  violet: '#a25bff',
  blue: '#4778ff',
  cyan: '#00b1ff',
  teal: '#04bb9f',
  lime: '#b6d80b',
  yellow: '#ffcc38',
  coral: '#ff8066',
} as const;
