// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/agent-creator/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { AgentCreator } from './AgentCreator.web';
export {
  AGENT_LANGUAGES,
  AGENT_SPEECH_RATES,
  DEFAULT_AGENT_PREFERENCES,
} from './constants';
export { normalizeAgentPreferences } from './shared';
export type {
  AgentCreatorAgent,
  AgentCreatorProps,
  AgentLanguage,
  AgentPreferences,
  AgentVoice,
} from './types';
