// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/scroll/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export { ScrollRestorationProvider } from './context';
export { useScrollRestoration } from './use-scroll-restoration.web';

export type {
  ScreenFocusEffect,
  ScrollableHandle,
  ScrollRestorationBinding,
  ScrollRestorationProviderProps,
  ScrollRestorationTarget,
  ScrollRouterAdapter,
  UseScrollRestorationOptions,
} from './types';
