// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/connection-status/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export type { ConnectionStatusToastsProps } from './shared';
// The hatch a consumer needs off Metro, where the optional `require` does not
// deliver the peer even when it is installed. See `netinfo.ts`.
export { provideNetInfo, type NetInfoLike } from './netinfo';
export {
  ConnectionStatusToasts,
} from './ConnectionStatusToasts.web';
