// AUTO-GENERATED by scripts/generate-platform-exports.mjs — DO NOT EDIT.
// Source of truth: src/list/index.ts.
// Re-run `bun run generate:exports` (or any `bun run build`) after
// changing that barrel or the set of web-forked subpaths.

export type {
  VirtualListHandle,
  VirtualListProps,
  VirtualListRenderItem,
  VirtualListRenderItemInfo,
  VirtualListSlot,
} from './types';
export {
  VirtualList,
} from './VirtualList.web';
export { default } from './VirtualList.web';
